# Generated by Django 5.2.8 on 2025-12-04 03:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('categories', 'Categories Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('categories_synced', models.IntegerField(default=0)),
                ('products_synced', models.IntegerField(default=0)),
                ('variations_synced', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Bespoke Sync Log',
                'verbose_name_plural': 'Bespoke Sync Logs',
                'db_table': 'bespoke_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AddonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per size/color at this tier and size', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this price')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now, help_text='Date this price becomes effective')),
                ('effective_to', models.DateField(blank=True, help_text='Date this price expires (NULL = no expiry)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_prices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Addon Price',
                'verbose_name_plural': 'Addon Prices',
                'db_table': 'bespoke_addon_price',
                'ordering': ['tier__addon_type', 'tier__sort_order', 'size_definition__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AddonPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_reason', models.TextField(help_text='Reason for price change')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('addon_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bespoke.addonprice')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_price_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Addon Price History',
                'verbose_name_plural': 'Addon Price Histories',
                'db_table': 'bespoke_addon_price_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='AddonPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('heat_transfer', 'Heat Transfer'), ('screen_print', 'Screen Print'), ('emb_applique', 'Embroidery/Applique')], db_index=True, help_text='Type of addon this tier applies to', max_length=50)),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity for this tier (inclusive)')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity for this tier (inclusive). NULL = unlimited', null=True)),
                ('display_label', models.CharField(help_text="Display label for tier (e.g., '1-9', '200+')", max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Addon Pricing Tier',
                'verbose_name_plural': 'Addon Pricing Tiers',
                'db_table': 'bespoke_addon_pricing_tier',
                'ordering': ['addon_type', 'sort_order', 'min_quantity'],
                'indexes': [models.Index(fields=['addon_type', 'is_active'], name='bespoke_add_addon_t_08dd74_idx')],
                'unique_together': {('addon_type', 'min_quantity', 'max_quantity')},
            },
        ),
        migrations.AddField(
            model_name='addonprice',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='bespoke.addonpricingtier'),
        ),
        migrations.CreateModel(
            name='AddonSizeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('heat_transfer', 'Heat Transfer'), ('screen_print', 'Screen Print'), ('emb_applique', 'Embroidery/Applique')], db_index=True, max_length=50)),
                ('size_code', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Size category code', max_length=20)),
                ('max_width_inches', models.DecimalField(decimal_places=2, help_text='Maximum width in inches', max_digits=5)),
                ('max_height_inches', models.DecimalField(decimal_places=2, help_text='Maximum height in inches', max_digits=5)),
                ('display_label', models.CharField(help_text='Display label (e.g., \'Small - up to 5" x 5"\')', max_length=100)),
                ('stitch_complexity', models.CharField(blank=True, choices=[('low', 'Low Stitch'), ('avg', 'Average Stitch'), ('lrg', 'Large Stitch')], help_text='Stitch complexity for embroidery (EMB only)', max_length=20, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Addon Size Definition',
                'verbose_name_plural': 'Addon Size Definitions',
                'db_table': 'bespoke_addon_size_definition',
                'ordering': ['addon_type', 'sort_order'],
                'unique_together': {('addon_type', 'size_code', 'stitch_complexity')},
            },
        ),
        migrations.AddField(
            model_name='addonprice',
            name='size_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='bespoke.addonsizedefinition'),
        ),
        migrations.CreateModel(
            name='BespokeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin7_id', models.CharField(db_index=True, help_text='CIN7 Category ID', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bespoke.bespokecategory')),
            ],
            options={
                'verbose_name': 'Bespoke Category',
                'verbose_name_plural': 'Bespoke Categories',
                'db_table': 'bespoke_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BespokeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin7_id', models.CharField(db_index=True, help_text='CIN7 Product ID', max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('product_type', models.CharField(choices=[('simple', 'Simple'), ('variable', 'Variable')], default='simple', max_length=20)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='CIN7 SKU/Code', max_length=100)),
                ('barcode', models.CharField(blank=True, help_text='CIN7 Barcode', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Product description')),
                ('short_description', models.TextField(blank=True, help_text='Short description')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price from CIN7', max_digits=10, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, help_text='Retail price from CIN7', max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price', max_digits=10, null=True)),
                ('margin_75_price', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated 75% margin price (cost ÷ 0.25)', max_digits=10, null=True)),
                ('stock_status', models.CharField(choices=[('instock', 'In Stock'), ('outofstock', 'Out of Stock'), ('onbackorder', 'On Backorder')], default='instock', max_length=20)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('stock_on_hand', models.IntegerField(blank=True, help_text='Stock on hand from CIN7', null=True)),
                ('stock_available', models.IntegerField(blank=True, help_text='Available stock from CIN7', null=True)),
                ('cin7_brand', models.CharField(blank=True, help_text='CIN7 Brand', max_length=100)),
                ('cin7_supplier', models.CharField(blank=True, help_text='CIN7 Supplier', max_length=100)),
                ('cin7_category_path', models.TextField(blank=True, help_text='Full category path from CIN7')),
                ('cin7_option1', models.CharField(blank=True, help_text='CIN7 Option1', max_length=100)),
                ('cin7_option2', models.CharField(blank=True, help_text='CIN7 Option2', max_length=100)),
                ('cin7_option3', models.CharField(blank=True, help_text='CIN7 Option3', max_length=100)),
                ('featured_image_url', models.URLField(blank=True, max_length=1000)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bespoke Product',
                'verbose_name_plural': 'Bespoke Products',
                'db_table': 'bespoke_product',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['product_type'], name='bespoke_pro_product_ad6863_idx'), models.Index(fields=['stock_status'], name='bespoke_pro_stock_s_e68d95_idx'), models.Index(fields=['cin7_brand'], name='bespoke_pro_cin7_br_ed24f7_idx'), models.Index(fields=['date_modified'], name='bespoke_pro_date_mo_67f2d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='BespokeProductCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='bespoke.bespokecategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='bespoke.bespokeproduct')),
            ],
            options={
                'verbose_name': 'Bespoke Product Category Assignment',
                'verbose_name_plural': 'Bespoke Product Category Assignments',
                'db_table': 'bespoke_product_category_assignment',
            },
        ),
        migrations.CreateModel(
            name='BespokeProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin7_id', models.CharField(db_index=True, help_text='CIN7 Variation ID', max_length=50, unique=True)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='CIN7 SKU/Code', max_length=100)),
                ('barcode', models.CharField(blank=True, help_text='CIN7 Barcode', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('option1_value', models.CharField(blank=True, help_text='Option 1 value (e.g., Color)', max_length=100)),
                ('option2_value', models.CharField(blank=True, help_text='Option 2 value (e.g., Size)', max_length=100)),
                ('option3_value', models.CharField(blank=True, help_text='Option 3 value', max_length=100)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price from CIN7', max_digits=10, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, help_text='Retail price from CIN7', max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price', max_digits=10, null=True)),
                ('margin_75_price', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated 75% margin price (cost ÷ 0.25)', max_digits=10, null=True)),
                ('stock_status', models.CharField(choices=[('instock', 'In Stock'), ('outofstock', 'Out of Stock'), ('onbackorder', 'On Backorder')], default='instock', max_length=20)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('stock_on_hand', models.IntegerField(blank=True, help_text='Stock on hand from CIN7', null=True)),
                ('stock_available', models.IntegerField(blank=True, help_text='Available stock from CIN7', null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='bespoke.bespokeproduct')),
            ],
            options={
                'verbose_name': 'Bespoke Product Variation',
                'verbose_name_plural': 'Bespoke Product Variations',
                'db_table': 'bespoke_product_variation',
                'ordering': ['parent_product', 'cin7_id'],
            },
        ),
        migrations.AddIndex(
            model_name='addonprice',
            index=models.Index(fields=['tier', 'size_definition', 'is_active'], name='bespoke_add_tier_id_db4a48_idx'),
        ),
        migrations.AddIndex(
            model_name='addonprice',
            index=models.Index(fields=['effective_from', 'effective_to'], name='bespoke_add_effecti_eef290_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addonprice',
            unique_together={('tier', 'size_definition', 'effective_from')},
        ),
        migrations.AlterUniqueTogether(
            name='bespokeproductcategoryassignment',
            unique_together={('product', 'category')},
        ),
        migrations.AddIndex(
            model_name='bespokeproductvariation',
            index=models.Index(fields=['parent_product', 'stock_status'], name='bespoke_pro_parent__4a44c2_idx'),
        ),
    ]
