# Generated by Django 5.2.6 on 2025-11-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespokeproductvariation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
