# Generated by Django 5.2.6 on 2025-11-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoke', '0002_alter_bespokeproductvariation_description'),
    ]

    operations = [
        # Add indexes for BespokeCategory
        migrations.AddIndex(
            model_name='bespokecategory',
            index=models.Index(fields=['slug'], name='bespoke_cat_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='bespokecategory',
            index=models.Index(fields=['is_active'], name='bespoke_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='bespokecategory',
            index=models.Index(fields=['parent'], name='bespoke_cat_parent_idx'),
        ),

        # Add indexes for BespokeProduct
        migrations.AddIndex(
            model_name='bespokeproduct',
            index=models.Index(fields=['is_active'], name='bespoke_prod_active_idx'),
        ),
        migrations.AddIndex(
            model_name='bespokeproduct',
            index=models.Index(fields=['product_type'], name='bespoke_prod_type_idx'),
        ),
        migrations.AddIndex(
            model_name='bespokeproduct',
            index=models.Index(fields=['slug'], name='bespoke_prod_slug_idx'),
        ),

        # Add indexes for BespokeProductVariation
        migrations.AddIndex(
            model_name='bespokeproductvariation',
            index=models.Index(fields=['is_active'], name='bespoke_var_active_idx'),
        ),
        migrations.AddIndex(
            model_name='bespokeproductvariation',
            index=models.Index(fields=['parent_product'], name='bespoke_var_parent_idx'),
        ),

        # Add compound index for BespokeProductCategoryAssignment
        migrations.AddIndex(
            model_name='bespokeproductcategoryassignment',
            index=models.Index(fields=['category', 'product'], name='bespoke_cat_assign_idx'),
        ),
    ]
