# Generated by Django 5.2.6 on 2025-11-14 02:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoke', '0003_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per size/color at this tier and size', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this price')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now, help_text='Date this price becomes effective')),
                ('effective_to', models.DateField(blank=True, help_text='Date this price expires (NULL = no expiry)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Addon Price',
                'verbose_name_plural': 'Addon Prices',
                'db_table': 'bespoke_addon_price',
                'ordering': ['tier__addon_type', 'tier__sort_order', 'size_definition__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AddonPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_reason', models.TextField(help_text='Reason for price change')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Addon Price History',
                'verbose_name_plural': 'Addon Price Histories',
                'db_table': 'bespoke_addon_price_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='AddonPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('heat_transfer', 'Heat Transfer'), ('screen_print', 'Screen Print'), ('emb_applique', 'Embroidery/Applique')], db_index=True, help_text='Type of addon this tier applies to', max_length=50)),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity for this tier (inclusive)')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity for this tier (inclusive). NULL = unlimited', null=True)),
                ('display_label', models.CharField(help_text="Display label for tier (e.g., '1-9', '200+')", max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Addon Pricing Tier',
                'verbose_name_plural': 'Addon Pricing Tiers',
                'db_table': 'bespoke_addon_pricing_tier',
                'ordering': ['addon_type', 'sort_order', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='AddonSizeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('heat_transfer', 'Heat Transfer'), ('screen_print', 'Screen Print'), ('emb_applique', 'Embroidery/Applique')], db_index=True, max_length=50)),
                ('size_code', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Size category code', max_length=20)),
                ('max_width_inches', models.DecimalField(decimal_places=2, help_text='Maximum width in inches', max_digits=5)),
                ('max_height_inches', models.DecimalField(decimal_places=2, help_text='Maximum height in inches', max_digits=5)),
                ('display_label', models.CharField(help_text='Display label (e.g., \'Small - up to 5" x 5"\')', max_length=100)),
                ('stitch_complexity', models.CharField(blank=True, choices=[('low', 'Low Stitch'), ('avg', 'Average Stitch'), ('lrg', 'Large Stitch')], help_text='Stitch complexity for embroidery (EMB only)', max_length=20, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Addon Size Definition',
                'verbose_name_plural': 'Addon Size Definitions',
                'db_table': 'bespoke_addon_size_definition',
                'ordering': ['addon_type', 'sort_order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='bespokecategory',
            name='bespoke_cat_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='bespokecategory',
            name='bespoke_cat_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='bespokecategory',
            name='bespoke_cat_parent_idx',
        ),
        migrations.RemoveIndex(
            model_name='bespokeproduct',
            name='bespoke_prod_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='bespokeproduct',
            name='bespoke_prod_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='bespokeproduct',
            name='bespoke_prod_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='bespokeproductcategoryassignment',
            name='bespoke_cat_assign_idx',
        ),
        migrations.RemoveIndex(
            model_name='bespokeproductvariation',
            name='bespoke_var_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='bespokeproductvariation',
            name='bespoke_var_parent_idx',
        ),
        migrations.AddField(
            model_name='addonprice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_prices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addonpricehistory',
            name='addon_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bespoke.addonprice'),
        ),
        migrations.AddField(
            model_name='addonpricehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_price_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='addonpricingtier',
            index=models.Index(fields=['addon_type', 'is_active'], name='bespoke_add_addon_t_08dd74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addonpricingtier',
            unique_together={('addon_type', 'min_quantity', 'max_quantity')},
        ),
        migrations.AddField(
            model_name='addonprice',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='bespoke.addonpricingtier'),
        ),
        migrations.AlterUniqueTogether(
            name='addonsizedefinition',
            unique_together={('addon_type', 'size_code', 'stitch_complexity')},
        ),
        migrations.AddField(
            model_name='addonprice',
            name='size_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='bespoke.addonsizedefinition'),
        ),
        migrations.AddIndex(
            model_name='addonprice',
            index=models.Index(fields=['tier', 'size_definition', 'is_active'], name='bespoke_add_tier_id_db4a48_idx'),
        ),
        migrations.AddIndex(
            model_name='addonprice',
            index=models.Index(fields=['effective_from', 'effective_to'], name='bespoke_add_effecti_eef290_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addonprice',
            unique_together={('tier', 'size_definition', 'effective_from')},
        ),
    ]
