# Generated by Django 5.2.6 on 2025-10-01 13:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('sales_rep', 'Sales Representative'), ('customer', 'Customer')], default='sales_rep', help_text='User type determines access level and permissions', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Department or team', max_length=100)),
                ('hire_date', models.DateField(blank=True, help_text='Date hired', null=True)),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID', max_length=50, null=True, unique=True)),
                ('is_active_sales_rep', models.BooleanField(default=True, help_text='Whether this sales rep is actively working assignments')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'authentication_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('password_change', 'Password Change'), ('assignment_created', 'Assignment Created'), ('assignment_updated', 'Assignment Updated'), ('assignment_deleted', 'Assignment Deleted'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('data_access', 'Data Access'), ('admin_action', 'Admin Action'), ('school_viewed', 'School Viewed'), ('school_searched', 'School Search'), ('school_list_viewed', 'School List Viewed'), ('school_detail_viewed', 'School Detail Viewed'), ('school_data_accessed', 'School Data Access'), ('wholesale_school_viewed', 'Wholesale School Viewed'), ('wholesale_school_searched', 'Wholesale School Search'), ('wholesale_school_created', 'Wholesale School Created'), ('wholesale_school_updated', 'Wholesale School Updated'), ('wholesale_school_deleted', 'Wholesale School Deleted'), ('wholesale_category_viewed', 'Wholesale Category Viewed'), ('wholesale_category_created', 'Wholesale Category Created'), ('wholesale_category_updated', 'Wholesale Category Updated'), ('wholesale_product_viewed', 'Wholesale Product Viewed'), ('wholesale_product_created', 'Wholesale Product Created'), ('wholesale_product_updated', 'Wholesale Product Updated'), ('wholesale_product_deleted', 'Wholesale Product Deleted'), ('wholesale_variation_created', 'Wholesale Variation Created'), ('wholesale_variation_updated', 'Wholesale Variation Updated'), ('wholesale_price_preview', 'Wholesale Price Preview'), ('wholesale_price_update', 'Wholesale Price Update'), ('wholesale_price_bulk_update', 'Wholesale Price Bulk Update'), ('wholesale_price_settings_accessed', 'Wholesale Price Settings Accessed'), ('wholesale_sync_started', 'Wholesale Sync Started'), ('wholesale_sync_completed', 'Wholesale Sync Completed'), ('wholesale_sync_failed', 'Wholesale Sync Failed'), ('tus_sync_started', 'TUS Sync Started'), ('tus_sync_completed', 'TUS Sync Completed'), ('tus_sync_failed', 'TUS Sync Failed'), ('sync_job_created', 'Sync Job Created'), ('sync_job_updated', 'Sync Job Updated'), ('sync_job_cancelled', 'Sync Job Cancelled'), ('csv_upload_started', 'CSV Upload Started'), ('csv_upload_completed', 'CSV Upload Completed'), ('csv_upload_failed', 'CSV Upload Failed'), ('csv_import_started', 'CSV Import Started'), ('csv_import_completed', 'CSV Import Completed'), ('csv_import_failed', 'CSV Import Failed'), ('data_export_requested', 'Data Export Requested'), ('data_export_completed', 'Data Export Completed'), ('tus_location_viewed', 'TUS Location Viewed'), ('tus_school_viewed', 'TUS School Viewed'), ('tus_category_viewed', 'TUS Category Viewed'), ('tus_product_viewed', 'TUS Product Viewed'), ('tus_search_performed', 'TUS Search Performed'), ('tus_variation_checked', 'TUS Variation Checked'), ('club_viewed', 'Club Viewed'), ('club_searched', 'Club Search'), ('club_list_viewed', 'Club List Viewed'), ('club_detail_viewed', 'Club Detail Viewed'), ('club_data_accessed', 'Club Data Access'), ('club_created', 'Club Created'), ('club_updated', 'Club Updated'), ('club_deleted', 'Club Deleted'), ('club_category_viewed', 'Club Category Viewed'), ('club_category_created', 'Club Category Created'), ('club_category_updated', 'Club Category Updated'), ('club_category_deleted', 'Club Category Deleted'), ('club_category_list_viewed', 'Club Category List Viewed'), ('club_product_viewed', 'Club Product Viewed'), ('club_product_created', 'Club Product Created'), ('club_product_updated', 'Club Product Updated'), ('club_product_deleted', 'Club Product Deleted'), ('club_product_searched', 'Club Product Search'), ('club_product_variation_viewed', 'Club Product Variation Viewed'), ('club_product_variation_created', 'Club Product Variation Created'), ('club_product_variation_updated', 'Club Product Variation Updated'), ('club_product_variation_deleted', 'Club Product Variation Deleted'), ('club_product_category_assigned', 'Club Product Category Assigned'), ('club_product_category_unassigned', 'Club Product Category Unassigned'), ('club_product_category_primary_changed', 'Club Product Category Primary Changed'), ('lotto_club_viewed', 'LOTTO Club Viewed'), ('lotto_club_searched', 'LOTTO Club Search'), ('lotto_product_viewed', 'LOTTO Product Viewed'), ('lotto_category_viewed', 'LOTTO Category Viewed'), ('lotto_variation_checked', 'LOTTO Variation Checked'), ('sas_club_viewed', 'SAS Club Viewed'), ('sas_club_searched', 'SAS Club Search'), ('sas_sport_viewed', 'SAS Sport Viewed'), ('sas_product_viewed', 'SAS Product Viewed'), ('sas_variation_checked', 'SAS Variation Checked'), ('club_sync_started', 'Club Sync Started'), ('club_sync_completed', 'Club Sync Completed'), ('club_sync_failed', 'Club Sync Failed'), ('lotto_sync_started', 'LOTTO Sync Started'), ('lotto_sync_completed', 'LOTTO Sync Completed'), ('lotto_sync_failed', 'LOTTO Sync Failed'), ('sas_sync_started', 'SAS Sync Started'), ('sas_sync_completed', 'SAS Sync Completed'), ('sas_sync_failed', 'SAS Sync Failed'), ('club_sync_job_created', 'Club Sync Job Created'), ('club_sync_job_updated', 'Club Sync Job Updated'), ('club_sync_job_cancelled', 'Club Sync Job Cancelled'), ('club_bulk_update', 'Club Bulk Update'), ('club_product_bulk_update', 'Club Product Bulk Update'), ('club_category_bulk_update', 'Club Category Bulk Update'), ('club_bulk_delete', 'Club Bulk Delete'), ('club_product_bulk_delete', 'Club Product Bulk Delete'), ('club_stock_updated', 'Club Stock Updated'), ('club_stock_status_changed', 'Club Stock Status Changed'), ('club_variation_stock_updated', 'Club Variation Stock Updated'), ('club_image_uploaded', 'Club Image Uploaded'), ('club_product_image_uploaded', 'Club Product Image Uploaded'), ('club_variation_image_uploaded', 'Club Variation Image Uploaded'), ('club_image_proxy_accessed', 'Club Image Proxy Accessed')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional action metadata')),
                ('affected_model', models.CharField(blank=True, help_text='Model that was affected', max_length=100)),
                ('affected_object_id', models.CharField(blank=True, help_text='ID of affected object', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SalesRepClubAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('club_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When assignment was made')),
                ('notes', models.TextField(blank=True, help_text='Notes about this assignment')),
                ('territory_name', models.CharField(blank=True, help_text='Territory or region name', max_length=100)),
                ('priority_level', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', help_text='Priority level for this assignment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['lottoclub', 'sasclub']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_club_assignments', to=settings.AUTH_USER_MODEL)),
                ('sales_rep', models.ForeignKey(limit_choices_to={'user_type': 'sales_rep'}, on_delete=django.db.models.deletion.CASCADE, related_name='club_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Rep Club Assignment',
                'verbose_name_plural': 'Sales Rep Club Assignments',
                'db_table': 'sales_rep_club_assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesRepSchoolAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When assignment was made')),
                ('notes', models.TextField(blank=True, help_text='Notes about this assignment')),
                ('territory_name', models.CharField(blank=True, help_text='Territory or region name', max_length=100)),
                ('priority_level', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', help_text='Priority level for this assignment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_assignments', to=settings.AUTH_USER_MODEL)),
                ('sales_rep', models.ForeignKey(limit_choices_to={'user_type': 'sales_rep'}, on_delete=django.db.models.deletion.CASCADE, related_name='school_assignments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, help_text='Regular school assignment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_assignments', to='schools.school')),
                ('wholesale_school', models.ForeignKey(blank=True, help_text='Wholesale school assignment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_assignments', to='schools.wholesaleschool')),
            ],
            options={
                'verbose_name': 'Sales Rep School Assignment',
                'verbose_name_plural': 'Sales Rep School Assignments',
                'db_table': 'sales_rep_school_assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active'], name='authenticat_user_ty_64fe8a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='authenticat_employe_00f71a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active_sales_rep'], name='authenticat_is_acti_272ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='audit_logs_action__11f9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['affected_model', 'affected_object_id'], name='audit_logs_affecte_921c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepschoolassignment',
            index=models.Index(fields=['sales_rep', 'is_active'], name='sales_rep_s_sales_r_4b44f2_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepschoolassignment',
            index=models.Index(fields=['school', 'is_active'], name='sales_rep_s_school__c65def_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepschoolassignment',
            index=models.Index(fields=['wholesale_school', 'is_active'], name='sales_rep_s_wholesa_e77f80_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepschoolassignment',
            index=models.Index(fields=['assigned_date'], name='sales_rep_s_assigne_174a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepschoolassignment',
            index=models.Index(fields=['territory_name'], name='sales_rep_s_territo_ce5351_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesrepschoolassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('school__isnull', False)), fields=('school',), name='unique_active_school_assignment'),
        ),
        migrations.AddConstraint(
            model_name='salesrepschoolassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('wholesale_school__isnull', False)), fields=('wholesale_school',), name='unique_active_wholesale_school_assignment'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='user_sessio_session_cc84b9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='user_sessio_last_ac_7cb421_idx'),
        ),
    ]
