# Generated by Django 5.2.8 on 2025-11-24 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepschoolassignment',
            name='tus_school',
            field=models.ForeignKey(blank=True, help_text='TUS school assignment (active business schools with products)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_assignments', to='schools.tusschool'),
        ),
        migrations.AddField(
            model_name='salesrepschoolassignment',
            name='wholesale_school',
            field=models.ForeignKey(blank=True, help_text='Wholesale school assignment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_assignments', to='schools.wholesaleschool'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type', 'is_active'], name='authenticat_user_ty_64fe8a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='authenticat_employe_00f71a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active_sales_rep'], name='authenticat_is_acti_272ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='audit_logs_action__11f9f1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['affected_model', 'affected_object_id'], name='audit_logs_affecte_921c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepschoolassignment',
            index=models.Index(fields=['sales_rep', 'is_active'], name='sales_rep_s_sales_r_4b44f2_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepschoolassignment',
            index=models.Index(fields=['tus_school', 'is_active'], name='sales_rep_s_tus_sch_b9914f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepschoolassignment',
            index=models.Index(fields=['wholesale_school', 'is_active'], name='sales_rep_s_wholesa_e77f80_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepschoolassignment',
            index=models.Index(fields=['assigned_date'], name='sales_rep_s_assigne_174a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrepschoolassignment',
            index=models.Index(fields=['territory_name'], name='sales_rep_s_territo_ce5351_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesrepschoolassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('tus_school__isnull', False)), fields=('tus_school',), name='unique_active_tus_school_assignment'),
        ),
        migrations.AddConstraint(
            model_name='salesrepschoolassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('wholesale_school__isnull', False)), fields=('wholesale_school',), name='unique_active_wholesale_school_assignment'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='user_sessio_session_cc84b9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='user_sessio_last_ac_7cb421_idx'),
        ),
    ]
