# Generated by Django 5.2.6 on 2025-10-02 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepclubassignment',
            name='sales_rep',
            field=models.ForeignKey(help_text='Sales representative or account manager assigned to this club', limit_choices_to={'user_type__in': ['sales_rep', 'account_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='club_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesrepschoolassignment',
            name='sales_rep',
            field=models.ForeignKey(help_text='Sales representative or account manager assigned to this school', limit_choices_to={'user_type__in': ['sales_rep', 'account_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='school_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales_rep', 'Sales Representative'), ('account_manager', 'Account Manager'), ('customer', 'Customer')], default='sales_rep', help_text='User type determines access level and permissions', max_length=20),
        ),
    ]
