# Generated by Django 5.2.6 on 2025-11-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Town/City', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, help_text='Postcode', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street number and name', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='suburb',
            field=models.CharField(blank=True, help_text='Suburb', max_length=100),
        ),
    ]
