# Generated by Django 5.2.6 on 2025-10-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_make_email_unique'),
        ('clubs', '0002_alter_syncjob_sync_type'),
        ('schools', '0003_wholesaleschool_logo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesrepschoolassignment',
            name='unique_active_school_assignment',
        ),
        migrations.RemoveIndex(
            model_name='salesrepschoolassignment',
            name='sales_rep_s_school__c65def_idx',
        ),
        migrations.RemoveField(
            model_name='salesrepschoolassignment',
            name='school',
        ),
        migrations.AddField(
            model_name='salesrepschoolassignment',
            name='tus_school',
            field=models.ForeignKey(blank=True, help_text='TUS school assignment (active business schools with products)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_assignments', to='clubs.tusschool'),
        ),
        migrations.AddIndex(
            model_name='salesrepschoolassignment',
            index=models.Index(fields=['tus_school', 'is_active'], name='sales_rep_s_tus_sch_b9914f_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesrepschoolassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('tus_school__isnull', False)), fields=('tus_school',), name='unique_active_tus_school_assignment'),
        ),
    ]
