# Generated by Django 5.2.6 on 2025-10-14 09:23

from django.db import migrations


def consolidate_quotation_audit_types(apps, schema_editor):
    """
    Consolidate granular quotation action types into 'quotation_updated'.
    Updates existing audit log entries and their descriptions.
    """
    AuditLog = apps.get_model('authentication', 'AuditLog')

    # Mapping of old action types to new descriptions
    action_mappings = {
        'quotation_item_added': 'Updated quotation: Added item',
        'quotation_item_updated': 'Updated quotation: Changed item quantity',
        'quotation_item_removed': 'Updated quotation: Removed item',
        'quotation_cart_cleared': 'Updated quotation: Cleared all items from cart',
        'quotation_edit_started': 'Updated quotation: Started editing quotation',
    }

    # Update each old action type
    for old_action, prefix in action_mappings.items():
        logs = AuditLog.objects.filter(action_type=old_action)
        for log in logs:
            # Keep the existing description but prefix it if it doesn't already have the prefix
            if not log.description.startswith('Updated quotation:'):
                # Extract meaningful info from old description
                if old_action == 'quotation_item_added':
                    if 'Added' in log.description:
                        log.description = log.description.replace('Added', 'Updated quotation: Added item')
                    elif 'Updated quantity' in log.description:
                        log.description = log.description.replace('Updated quantity for', 'Updated quotation: Changed')
                    else:
                        log.description = f'{prefix}: {log.description}'
                elif old_action == 'quotation_item_updated':
                    if 'Updated' in log.description and 'quantity from' in log.description:
                        log.description = log.description.replace('Updated', 'Updated quotation: Changed')
                    else:
                        log.description = f'{prefix}: {log.description}'
                elif old_action == 'quotation_item_removed':
                    if 'Removed' in log.description:
                        log.description = log.description.replace('Removed', 'Updated quotation: Removed item')
                    else:
                        log.description = f'{prefix}: {log.description}'
                elif old_action == 'quotation_cart_cleared':
                    log.description = 'Updated quotation: Cleared all items from cart'
                elif old_action == 'quotation_edit_started':
                    if 'Started editing' in log.description:
                        log.description = log.description.replace('Started editing', 'Updated quotation: Started editing')
                    else:
                        log.description = f'{prefix}: {log.description}'

            # Update action type
            log.action_type = 'quotation_updated'
            log.save(update_fields=['action_type', 'description'])

    # Also remove obsolete action types that are no longer valid
    # These were part of the model but may not be in use
    obsolete_types = [
        'quotation_confirmed',
        'quotation_cancelled',
        'quotation_expired',
        'quotation_status_changed',
    ]

    for obsolete in obsolete_types:
        # Convert to generic quotation_updated, keeping existing description
        logs = AuditLog.objects.filter(action_type=obsolete)
        for log in logs:
            log.action_type = 'quotation_updated'
            log.save(update_fields=['action_type'])


def reverse_consolidation(apps, schema_editor):
    """
    Reverse migration is not possible as we've lost the original action type information.
    This is acceptable as the consolidation is a one-way data cleanup.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_quotation_audit_action_types'),
    ]

    operations = [
        migrations.RunPython(consolidate_quotation_audit_types, reverse_consolidation),
    ]
