# Generated by Django 5.2.6 on 2025-10-14 09:24

from django.db import migrations


def consolidate_quotation_logs(apps, schema_editor):
    """
    Consolidate granular quotation action types into 'quotation_updated'
    while preserving context in descriptions.
    """
    AuditLog = apps.get_model('authentication', 'AuditLog')

    # Map old action types to new ones
    action_mapping = {
        'quotation_item_added': 'quotation_updated',
        'quotation_item_updated': 'quotation_updated',
        'quotation_item_removed': 'quotation_updated',
        'quotation_cart_cleared': 'quotation_updated',
        'quotation_edit_started': 'quotation_updated',
        'quotation_status_changed': 'quotation_updated',
        'quotation_confirmed': 'quotation_approved',
        'quotation_cancelled': 'quotation_updated',
        'quotation_expired': 'quotation_updated',
    }

    # Update logs in batches
    for old_action, new_action in action_mapping.items():
        logs = AuditLog.objects.filter(action_type=old_action)

        for log in logs:
            # Update action type
            log.action_type = new_action

            # Enhance description if needed
            if not log.description.startswith('Updated quotation:'):
                if old_action == 'quotation_item_added' and 'Added' in log.description:
                    log.description = f"Updated quotation: {log.description}"
                elif old_action == 'quotation_item_updated' and 'Updated' in log.description:
                    log.description = f"Updated quotation: {log.description.replace('Updated', 'Changed', 1)}"
                elif old_action == 'quotation_item_removed' and 'Removed' in log.description:
                    log.description = f"Updated quotation: {log.description}"
                elif old_action == 'quotation_cart_cleared':
                    log.description = "Updated quotation: Cleared all items from cart"
                elif old_action == 'quotation_edit_started':
                    log.description = f"Updated quotation: {log.description.replace('Started editing', 'Editing started for', 1)}"

            log.save(update_fields=['action_type', 'description'])

    print(f"Consolidated {sum(AuditLog.objects.filter(action_type__in=action_mapping.keys()).count() for _ in [1])} audit log entries")


def reverse_consolidation(apps, schema_editor):
    """
    Reverse migration - not fully reversible since we lose some granularity,
    but we can convert back to quotation_updated for all.
    """
    pass  # Data migration reversal is not critical


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.RunPython(consolidate_quotation_logs, reverse_consolidation),
    ]
