"""
Django settings for kitup project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Configure PyMySQL to work with Django's MySQL backend
import pymysql
pymysql.install_as_MySQLdb()

# Configure PyMySQL to work with Django
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-)71e$mb1*qcx_#+24zjp6f6u149@uw_4k#wd8h7su)lxuh^=y6')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Django REST Framework
    'rest_framework',
    'django_filters',
    'rest_framework_csv',
    'drf_yasg',

    # Local apps
    'authentication',
    'clubs',
    'schools',
    'quotations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.AuthenticationMiddleware',
    'authentication.middleware.RoleBasedAccessMiddleware',
    'authentication.middleware.SessionSecurityMiddleware',
]

ROOT_URLCONF = 'kitup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'quotations.context_processors.quotation_cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'kitup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# For development and migration generation, we can use SQLite
# Switch to MySQL in production by setting USE_MYSQL=True in .env
USE_MYSQL = config('USE_MYSQL', default=False, cast=bool)

if USE_MYSQL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='3306', cast=int),
            'OPTIONS': {
                'sql_mode': 'traditional',
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django.log',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'clubs': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_csv.renderers.CSVRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FileUploadParser',
    ],
}

# Swagger/OpenAPI Configuration
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'basic': {
            'type': 'basic'
        }
    },
    'USE_SESSION_AUTH': True,
    'JSON_EDITOR': True,
    'SUPPORTED_SUBMIT_METHODS': [
        'get',
        'post',
        'put',
        'delete',
        'patch'
    ],
    'OPERATIONS_SORTER': 'alpha',
    'TAGS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'DEEP_LINKING': True,
    'SHOW_EXTENSIONS': True,
    'DEFAULT_MODEL_RENDERING': 'example'
}

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_TEMP_DIR = BASE_DIR / 'temp_uploads'

# Ensure temp directory exists
FILE_UPLOAD_TEMP_DIR.mkdir(exist_ok=True)

# LOTTO Sports Configuration
LOTTO_SITE_URL = config('LOTTO_SITE_URL', default='https://dev-lottosports.it.sas.co.nz')
LOTTO_WOO_URL = config('LOTTO_WOOCOMMERCE_API_URL')
LOTTO_WOO_KEY = config('LOTTO_WOOCOMMERCE_API_CONSUMER_KEY')
LOTTO_WOO_SECRET = config('LOTTO_WOOCOMMERCE_API_SECRET')

# WooCommerce API Configuration for SAS
SAS_WOO_URL = config('SAS_WOOCOMMERCE_API_URL')
SAS_WOO_KEY = config('SAS_WOOCOMMERCE_API_CONSUMER_KEY')
SAS_WOO_SECRET = config('SAS_WOOCOMMERCE_API_SECRET')

# CIN7 API Configuration for Wholesale Schools
CIN7_API_URL = config('CIN7_API_URL', default='https://api.cin7.com/api/v1/')
CIN7_API_KEY = config('CIN7_API_KEY', default='')
CIN7_API_SECRET = config('CIN7_API_SECRET', default='')
CIN7_ACCOUNT_ID = config('CIN7_ACCOUNT_ID', default='')

# CIN7 API Settings
CIN7_TIMEOUT = config('CIN7_TIMEOUT', default=30, cast=int)
CIN7_MAX_RETRIES = config('CIN7_MAX_RETRIES', default=3, cast=int)
CIN7_BATCH_SIZE = config('CIN7_BATCH_SIZE', default=100, cast=int)

# Custom User Model
AUTH_USER_MODEL = 'authentication.User'

# Authentication Backends - use email for login
AUTHENTICATION_BACKENDS = [
    'authentication.backends.EmailBackend',  # Custom email authentication
    'django.contrib.auth.backends.ModelBackend',  # Fallback to username (for admin)
]

# Authentication Settings
LOGIN_URL = '/'  # Home page is the login page
LOGIN_REDIRECT_URL = '/clubs/dashboard/'
LOGOUT_REDIRECT_URL = '/'  # Redirect to home page with login form

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Explicit database backend
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Set to False for testing - cookies persist
SESSION_SAVE_EVERY_REQUEST = True  # Required for session persistence with custom middleware
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Allow cookies on redirects
SESSION_COOKIE_SECURE = False  # Allow cookies over HTTP for development
SESSION_COOKIE_PATH = '/'  # Ensure cookie is valid for entire site
SESSION_COOKIE_NAME = 'sessionid'  # Explicit session cookie name
SESSION_COOKIE_DOMAIN = None  # Explicitly set to None for localhost
