# Generated by Django 5.2.8 on 2025-11-24 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BallStoreSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('categories', 'Categories Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('categories_synced', models.IntegerField(default=0)),
                ('products_synced', models.IntegerField(default=0)),
                ('variations_synced', models.IntegerField(default=0)),
                ('images_synced', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'BallStore Sync Log',
                'verbose_name_plural': 'BallStore Sync Logs',
                'db_table': 'ballstore_sync_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BallStoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_id', models.IntegerField(help_text='WooCommerce Category ID', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_type', models.CharField(default='default', max_length=50)),
                ('product_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ballstore.ballstorecategory')),
            ],
            options={
                'verbose_name': 'BallStore Category',
                'verbose_name_plural': 'BallStore Categories',
                'db_table': 'ballstore_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BallStoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_id', models.IntegerField(help_text='WooCommerce Product ID', unique=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('permalink', models.URLField(blank=True, max_length=1000)),
                ('product_type', models.CharField(choices=[('simple', 'Simple'), ('variable', 'Variable')], default='simple', max_length=20)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='Full HTML description')),
                ('short_description', models.TextField(blank=True, help_text='Short HTML description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price from CIN7 API', max_digits=10, null=True)),
                ('margin_75_price', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated 75% margin price (cost ÷ 0.25)', max_digits=10, null=True)),
                ('stock_status', models.CharField(choices=[('instock', 'In Stock'), ('outofstock', 'Out of Stock'), ('onbackorder', 'On Backorder')], default='instock', max_length=20)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('manage_stock', models.BooleanField(default=False)),
                ('featured_image_url', models.URLField(blank=True, max_length=1000)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='ballstore.ballstorecategory')),
            ],
            options={
                'verbose_name': 'BallStore Product',
                'verbose_name_plural': 'BallStore Products',
                'db_table': 'ballstore_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BallStoreProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_id', models.IntegerField(help_text='WooCommerce Image ID')),
                ('src', models.URLField(max_length=1000)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ballstore.ballstoreproduct')),
            ],
            options={
                'verbose_name': 'BallStore Product Image',
                'verbose_name_plural': 'BallStore Product Images',
                'db_table': 'ballstore_product_image',
                'ordering': ['product', 'position'],
            },
        ),
        migrations.CreateModel(
            name='BallStoreProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_id', models.IntegerField(help_text='WooCommerce Variation ID', unique=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price from CIN7 API', max_digits=10, null=True)),
                ('margin_75_price', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated 75% margin price (cost ÷ 0.25)', max_digits=10, null=True)),
                ('stock_status', models.CharField(choices=[('instock', 'In Stock'), ('outofstock', 'Out of Stock'), ('onbackorder', 'On Backorder')], default='instock', max_length=20)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('manage_stock', models.BooleanField(default=False)),
                ('attributes', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='ballstore.ballstoreproduct')),
            ],
            options={
                'verbose_name': 'BallStore Product Variation',
                'verbose_name_plural': 'BallStore Product Variations',
                'db_table': 'ballstore_product_variation',
                'ordering': ['parent_product', 'wc_id'],
            },
        ),
        migrations.AddIndex(
            model_name='ballstoreproduct',
            index=models.Index(fields=['product_type'], name='ballstore_p_product_093d48_idx'),
        ),
        migrations.AddIndex(
            model_name='ballstoreproduct',
            index=models.Index(fields=['stock_status'], name='ballstore_p_stock_s_9fc26e_idx'),
        ),
        migrations.AddIndex(
            model_name='ballstoreproduct',
            index=models.Index(fields=['date_modified'], name='ballstore_p_date_mo_8571c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ballstoreproductimage',
            unique_together={('product', 'wc_id')},
        ),
        migrations.AddIndex(
            model_name='ballstoreproductvariation',
            index=models.Index(fields=['parent_product', 'stock_status'], name='ballstore_p_parent__de6835_idx'),
        ),
    ]
