# Generated by Django 5.2.6 on 2025-11-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballstore', '0001_initial'),
    ]

    operations = [
        # Add CIN7 price fields to BallStoreProduct
        migrations.AddField(
            model_name='ballstoreproduct',
            name='cost_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Cost price from CIN7 API',
                max_digits=10,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='ballstoreproduct',
            name='margin_75_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Calculated 75% margin price (cost ÷ 0.25)',
                max_digits=10,
                null=True
            ),
        ),
        # Add CIN7 price fields to BallStoreProductVariation
        migrations.AddField(
            model_name='ballstoreproductvariation',
            name='cost_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Cost price from CIN7 API',
                max_digits=10,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='ballstoreproductvariation',
            name='margin_75_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Calculated 75% margin price (cost ÷ 0.25)',
                max_digits=10,
                null=True
            ),
        ),
    ]
