# Generated by Django 5.2.5 on 2025-09-03 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Club name', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name', max_length=255, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Club website URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('address', models.TextField(blank=True, help_text='Club physical address', null=True)),
                ('club_type', models.CharField(choices=[('LOTTO', 'LOTTO'), ('SAS', 'SAS')], default='LOTTO', help_text='Type of club', max_length=10)),
                ('sport_tag', models.CharField(choices=[('Football', 'Football'), ('Rugby', 'Rugby'), ('Cricket', 'Cricket'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Volleyball', 'Volleyball'), ('Hockey', 'Hockey'), ('Netball', 'Netball'), ('Other', 'Other')], default='Football', help_text='Primary sport', max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Club logo image', null=True, upload_to='clubs/images/')),
                ('woo_category_id', models.PositiveIntegerField(help_text='WooCommerce category ID', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the club is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['club_type', 'is_active'], name='clubs_club_club_ty_ae3a18_idx'), models.Index(fields=['woo_category_id'], name='clubs_club_woo_cat_8833f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name', max_length=255)),
                ('woo_category_id', models.PositiveIntegerField(help_text='WooCommerce category ID', unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Category image', null=True, upload_to='categories/images/')),
                ('product_count', models.PositiveIntegerField(default=0, help_text='Number of products in this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club Category',
                'verbose_name_plural': 'Club Categories',
                'ordering': ['club', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name', max_length=255)),
                ('woo_product_id', models.PositiveIntegerField(help_text='WooCommerce product ID', unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('short_description', models.TextField(blank=True, help_text='Short product description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Product image', null=True, upload_to='products/images/')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100, null=True)),
                ('stock_status', models.CharField(choices=[('instock', 'In Stock'), ('outofstock', 'Out of Stock'), ('onbackorder', 'On Backorder')], default='instock', max_length=20)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.CharField(blank=True, help_text='Product weight', max_length=50, null=True)),
                ('dimensions', models.JSONField(blank=True, help_text='Product dimensions', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Product tags', null=True)),
                ('attributes', models.JSONField(blank=True, help_text='Product attributes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clubs.clubcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='clubcategory',
            index=models.Index(fields=['club', 'product_count'], name='clubs_clubc_club_id_a23ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='clubcategory',
            index=models.Index(fields=['woo_category_id'], name='clubs_clubc_woo_cat_9d0574_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clubcategory',
            unique_together={('club', 'name')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'stock_status'], name='clubs_produ_categor_c2eeb8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['woo_product_id'], name='clubs_produ_woo_pro_a9f87a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='clubs_produ_sku_11ab0d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='clubs_produ_price_df0b5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'name')},
        ),
    ]
