# Generated by Django 5.2.5 on 2025-09-03 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('material', 'Material'), ('style', 'Style'), ('gender', 'Gender'), ('age_group', 'Age Group'), ('other', 'Other')], help_text='Type of variation', max_length=50)),
                ('variation_value', models.CharField(help_text="Variation value (e.g., 'Large', 'Red', 'Cotton')", max_length=255)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, help_text='Price adjustment (+/-) from base product price', max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Stock quantity for this variation')),
                ('sku_suffix', models.CharField(blank=True, help_text='SKU suffix for this variation', max_length=50, null=True)),
                ('woo_variation_id', models.PositiveIntegerField(help_text='WooCommerce variation ID', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this variation is active')),
                ('attributes', models.JSONField(blank=True, help_text='WooCommerce variation attributes', null=True)),
                ('image', models.ImageField(blank=True, help_text='Variation-specific image', null=True, upload_to='variations/images/')),
                ('weight', models.CharField(blank=True, help_text='Variation weight', max_length=50, null=True)),
                ('dimensions', models.JSONField(blank=True, help_text='Variation dimensions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='clubs.product')),
            ],
            options={
                'verbose_name': 'Product Variation',
                'verbose_name_plural': 'Product Variations',
                'ordering': ['product', 'variation_type', 'variation_value'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='clubs_produ_product_eeeb8b_idx'), models.Index(fields=['woo_variation_id'], name='clubs_produ_woo_var_1aeeb8_idx'), models.Index(fields=['variation_type', 'variation_value'], name='clubs_produ_variati_914ee8_idx'), models.Index(fields=['stock_quantity'], name='clubs_produ_stock_q_568196_idx')],
                'unique_together': {('product', 'variation_type', 'variation_value')},
            },
        ),
    ]
