# Generated by Django 5.2.6 on 2025-10-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottoclub',
            name='is_generic_shop',
            field=models.BooleanField(default=False, help_text='Whether this is a generic shop category (Footwear, Teamwear, etc.)'),
        ),
        migrations.AddIndex(
            model_name='lottoclub',
            index=models.Index(fields=['is_generic_shop', 'is_active'], name='lotto_clubs_is_gene_0c058e_idx'),
        ),
    ]
