# Generated by Django 5.2.5 on 2025-09-14 05:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SASSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Sport name (e.g., Basketball)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version', max_length=100, unique=True)),
                ('woo_category_id', models.PositiveIntegerField(help_text='WooCommerce category ID for this sport', unique=True)),
                ('description', models.TextField(blank=True, help_text='Sport description')),
                ('image_url', models.URLField(blank=True, help_text='Sport category image URL', validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sport is active')),
                ('club_count', models.PositiveIntegerField(default=0, help_text='Number of active clubs in this sport')),
                ('product_count', models.PositiveIntegerField(default=0, help_text='Total products across all clubs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last WooCommerce sync timestamp', null=True)),
            ],
            options={
                'verbose_name': 'SAS Sport',
                'verbose_name_plural': 'SAS Sports',
                'db_table': 'sas_sports',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['woo_category_id'], name='sas_sports_woo_cat_ff73c2_idx'), models.Index(fields=['is_active', 'club_count'], name='sas_sports_is_acti_a4aa65_idx'), models.Index(fields=['name'], name='sas_sports_name_b50f38_idx'), models.Index(fields=['last_sync_at'], name='sas_sports_last_sy_7adf65_idx')],
            },
        ),
        migrations.CreateModel(
            name='SASClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Club name', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version', max_length=255)),
                ('woo_category_id', models.PositiveIntegerField(help_text='WooCommerce category ID for this club', unique=True)),
                ('description', models.TextField(blank=True, help_text='Club description')),
                ('image_url', models.URLField(blank=True, help_text='Club logo/image URL', validators=[django.core.validators.URLValidator()])),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Club website', validators=[django.core.validators.URLValidator()])),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('city', models.CharField(blank=True, help_text='City/Location', max_length=100)),
                ('province', models.CharField(blank=True, help_text='Province', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Full address')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this club is active')),
                ('is_school', models.BooleanField(default=False, help_text='Whether this is identified as a school')),
                ('product_count', models.PositiveIntegerField(default=0, help_text='Number of products for this club')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last WooCommerce sync timestamp', null=True)),
                ('sport', models.ForeignKey(help_text='Sport this club belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='clubs.sassport')),
            ],
            options={
                'verbose_name': 'SAS Club',
                'verbose_name_plural': 'SAS Clubs',
                'db_table': 'sas_clubs',
                'ordering': ['sport__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SASProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version', max_length=255)),
                ('woo_product_id', models.PositiveIntegerField(help_text='WooCommerce product ID', unique=True)),
                ('product_type', models.CharField(choices=[('simple', 'Simple'), ('grouped', 'Grouped'), ('external', 'External'), ('variable', 'Variable')], default='simple', max_length=20)),
                ('stock_status', models.CharField(choices=[('instock', 'In Stock'), ('outofstock', 'Out of Stock'), ('onbackorder', 'On Backorder')], default='instock', max_length=20)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current selling price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, help_text='Regular price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price (if on sale)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True, help_text='Full product description')),
                ('short_description', models.TextField(blank=True, help_text='Short product description')),
                ('weight', models.CharField(blank=True, help_text='Product weight', max_length=50)),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='Product dimensions')),
                ('image_url', models.URLField(blank=True, help_text='Main product image URL', validators=[django.core.validators.URLValidator()])),
                ('gallery_urls', models.JSONField(blank=True, default=list, help_text='Additional product images')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Product tags')),
                ('attributes', models.JSONField(blank=True, default=list, help_text='Product attributes')),
                ('categories', models.JSONField(blank=True, default=list, help_text='Additional WooCommerce categories')),
                ('featured', models.BooleanField(default=False, help_text='Whether product is featured')),
                ('catalog_visibility', models.CharField(default='visible', help_text='Catalog visibility', max_length=20)),
                ('manage_stock', models.BooleanField(default=False)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('backorders', models.CharField(default='no', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last WooCommerce sync timestamp', null=True)),
                ('club', models.ForeignKey(help_text='Club this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clubs.sasclub')),
            ],
            options={
                'verbose_name': 'SAS Product',
                'verbose_name_plural': 'SAS Products',
                'db_table': 'sas_products',
                'ordering': ['club__sport__name', 'club__name', 'name'],
                'indexes': [models.Index(fields=['club', 'stock_status'], name='sas_product_club_id_791286_idx'), models.Index(fields=['woo_product_id'], name='sas_product_woo_pro_e80769_idx'), models.Index(fields=['sku'], name='sas_product_sku_63e3a5_idx'), models.Index(fields=['price'], name='sas_product_price_253e66_idx'), models.Index(fields=['stock_status'], name='sas_product_stock_s_e94ba3_idx'), models.Index(fields=['featured', 'stock_status'], name='sas_product_feature_04f690_idx'), models.Index(fields=['created_at'], name='sas_product_created_b34551_idx'), models.Index(fields=['last_sync_at'], name='sas_product_last_sy_85dd38_idx'), models.Index(fields=['club', 'featured'], name='sas_product_club_id_3580d1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sasclub',
            index=models.Index(fields=['sport', 'is_active'], name='sas_clubs_sport_i_f85e53_idx'),
        ),
        migrations.AddIndex(
            model_name='sasclub',
            index=models.Index(fields=['woo_category_id'], name='sas_clubs_woo_cat_c04853_idx'),
        ),
        migrations.AddIndex(
            model_name='sasclub',
            index=models.Index(fields=['name'], name='sas_clubs_name_b637e2_idx'),
        ),
        migrations.AddIndex(
            model_name='sasclub',
            index=models.Index(fields=['is_school', 'is_active'], name='sas_clubs_is_scho_44bfc0_idx'),
        ),
        migrations.AddIndex(
            model_name='sasclub',
            index=models.Index(fields=['product_count'], name='sas_clubs_product_52283f_idx'),
        ),
        migrations.AddIndex(
            model_name='sasclub',
            index=models.Index(fields=['last_sync_at'], name='sas_clubs_last_sy_efecd5_idx'),
        ),
        migrations.AddIndex(
            model_name='sasclub',
            index=models.Index(fields=['sport', 'product_count'], name='sas_clubs_sport_i_e947a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sasclub',
            unique_together={('sport', 'name')},
        ),
    ]
