# Generated by Django 5.2.6 on 2025-10-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='sync_type',
            field=models.CharField(choices=[('lotto', 'LOTTO Clubs'), ('sas', 'SAS Clubs'), ('tus', 'TUS Schools'), ('wholesale', 'Wholesale Schools'), ('nz', 'NZ Government Schools')], help_text='Type of sync operation', max_length=10),
        ),
    ]
