# Generated by Django 5.2.5 on 2025-09-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_create_sas_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sasclub',
            name='is_generic_category',
            field=models.BooleanField(default=False, help_text='Whether this is a generic product category'),
        ),
        migrations.AddIndex(
            model_name='sasclub',
            index=models.Index(fields=['is_generic_category', 'is_active'], name='sas_clubs_is_gene_c38782_idx'),
        ),
        migrations.AddIndex(
            model_name='sasclub',
            index=models.Index(fields=['is_school', 'is_generic_category', 'is_active'], name='sas_clubs_is_scho_1537da_idx'),
        ),
    ]
