# Generated by Django 5.2.5 on 2025-09-03 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_add_product_variations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('lotto', 'LOTTO Clubs'), ('sas', 'SAS Clubs')], help_text='Type of sync operation', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, help_text='Progress from 0 to 100')),
                ('current_step', models.CharField(blank=True, help_text='Current operation being performed', max_length=255)),
                ('clubs_created', models.PositiveIntegerField(default=0)),
                ('clubs_updated', models.PositiveIntegerField(default=0)),
                ('categories_created', models.PositiveIntegerField(default=0)),
                ('categories_updated', models.PositiveIntegerField(default=0)),
                ('products_created', models.PositiveIntegerField(default=0)),
                ('products_updated', models.PositiveIntegerField(default=0)),
                ('log_messages', models.JSONField(default=list, help_text='Array of log messages')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error code for programmatic handling', max_length=50, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Job',
                'verbose_name_plural': 'Sync Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'sync_type'], name='clubs_syncj_status_5bfcb7_idx'), models.Index(fields=['created_at'], name='clubs_syncj_created_ab73b0_idx')],
            },
        ),
    ]
