# Generated by Django 5.2.6 on 2025-10-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_syncjob_sync_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sasclub',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='lottoclub',
            index=models.Index(fields=['slug'], name='lotto_clubs_slug_b806a0_idx'),
        ),
        migrations.AddIndex(
            model_name='sasclub',
            index=models.Index(fields=['slug'], name='sas_clubs_slug_434fef_idx'),
        ),
        migrations.AddIndex(
            model_name='tusschool',
            index=models.Index(fields=['slug'], name='tus_schools_slug_7fec59_idx'),
        ),
    ]
