# Generated by Django 5.2.6 on 2025-11-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_add_is_generic_shop_to_lotto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='sync_type',
            field=models.CharField(choices=[('lotto', 'LOTTO Clubs'), ('sas', 'SAS Clubs'), ('tus', 'TUS Schools'), ('wholesale', 'Wholesale Schools'), ('nz', 'NZ Government Schools'), ('bespoke', 'Bespoke Products')], help_text='Type of sync operation', max_length=10),
        ),
    ]
