# Generated by Django 5.2.6 on 2025-11-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_syncjob_sync_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_company_name',
            field=models.CharField(blank=True, help_text='CIN7 Contact company name', max_length=255),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_email',
            field=models.EmailField(blank=True, help_text='CIN7 Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_id',
            field=models.CharField(blank=True, db_index=True, help_text='CIN7 Contact ID for sales orders', max_length=50),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_company_name',
            field=models.CharField(blank=True, help_text='CIN7 Contact company name', max_length=255),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_email',
            field=models.EmailField(blank=True, help_text='CIN7 Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_id',
            field=models.CharField(blank=True, db_index=True, help_text='CIN7 Contact ID for sales orders', max_length=50),
        ),
    ]
