# Generated by Django 5.2.5 on 2025-09-15 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_add_generic_category_detection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SASProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('colour', 'Colour'), ('material', 'Material'), ('style', 'Style'), ('gender', 'Gender'), ('age_group', 'Age Group'), ('other', 'Other')], help_text='Type of variation', max_length=50)),
                ('variation_value', models.CharField(help_text="Variation value (e.g., 'Large', 'Red', 'Cotton')", max_length=255)),
                ('woo_variation_id', models.PositiveIntegerField(blank=True, help_text='WooCommerce variation ID', null=True, unique=True)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, help_text='Price adjustment (+/-) from base product price', max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Stock quantity for this variation')),
                ('sku_suffix', models.CharField(blank=True, help_text='SKU suffix for this variation', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this variation is active')),
                ('attributes', models.JSONField(blank=True, help_text='Additional variation attributes', null=True)),
                ('weight', models.CharField(blank=True, help_text='Variation weight', max_length=50, null=True)),
                ('dimensions', models.JSONField(blank=True, help_text='Variation dimensions', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Variation-specific image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='clubs.sasproduct')),
            ],
            options={
                'verbose_name': 'SAS Product Variation',
                'verbose_name_plural': 'SAS Product Variations',
                'db_table': 'sas_product_variations',
                'ordering': ['product', 'variation_type', 'variation_value'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='sas_product_product_11ed9e_idx'), models.Index(fields=['woo_variation_id'], name='sas_product_woo_var_fbb808_idx'), models.Index(fields=['variation_type', 'variation_value'], name='sas_product_variati_0b9b5c_idx'), models.Index(fields=['stock_quantity'], name='sas_product_stock_q_4e8297_idx'), models.Index(fields=['created_at'], name='sas_product_created_523e27_idx')],
                'unique_together': {('product', 'variation_type', 'variation_value')},
            },
        ),
    ]
