# Generated by Django 5.2.6 on 2025-10-05 16:05

from django.db import migrations
from django.utils.text import slugify


def populate_slugs_forward(apps, schema_editor):
    """Populate slugs for all institution models that don't have them"""

    # Get model classes
    TUSSchool = apps.get_model('clubs', 'TUSSchool')
    LottoClub = apps.get_model('clubs', 'LottoClub')
    SASClub = apps.get_model('clubs', 'SASClub')
    WholesaleSchool = apps.get_model('schools', 'WholesaleSchool')

    # Helper function to generate unique slug
    def generate_unique_slug(model_class, base_text, instance_pk=None):
        base_slug = slugify(base_text)
        slug = base_slug
        counter = 1

        queryset = model_class.objects.filter(slug=slug)
        if instance_pk:
            queryset = queryset.exclude(pk=instance_pk)

        while queryset.exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
            queryset = model_class.objects.filter(slug=slug)
            if instance_pk:
                queryset = queryset.exclude(pk=instance_pk)

        return slug

    # Populate TUS School slugs
    for school in TUSSchool.objects.filter(slug=''):
        location_name = school.location.name if school.location else 'school'
        slug_text = f"{location_name}-{school.name}"
        school.slug = generate_unique_slug(TUSSchool, slug_text, school.pk)
        school.save(update_fields=['slug'])

    # Populate LOTTO Club slugs
    for club in LottoClub.objects.filter(slug=''):
        club.slug = generate_unique_slug(LottoClub, club.name, club.pk)
        club.save(update_fields=['slug'])

    # Populate SAS Club slugs
    for club in SASClub.objects.filter(slug=''):
        club.slug = generate_unique_slug(SASClub, club.name, club.pk)
        club.save(update_fields=['slug'])

    # Populate Wholesale School slugs
    for school in WholesaleSchool.objects.filter(slug=''):
        school.slug = generate_unique_slug(WholesaleSchool, school.name, school.pk)
        school.save(update_fields=['slug'])


def populate_slugs_reverse(apps, schema_editor):
    """Reverse migration - clear all slugs"""
    TUSSchool = apps.get_model('clubs', 'TUSSchool')
    LottoClub = apps.get_model('clubs', 'LottoClub')
    SASClub = apps.get_model('clubs', 'SASClub')
    WholesaleSchool = apps.get_model('schools', 'WholesaleSchool')

    TUSSchool.objects.all().update(slug='')
    LottoClub.objects.all().update(slug='')
    SASClub.objects.all().update(slug='')
    WholesaleSchool.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_sasclub_slug_and_more'),
        ('schools', '0004_wholesaleschool_wholesale_s_slug_dfe389_idx'),
    ]

    operations = [
        migrations.RunPython(populate_slugs_forward, populate_slugs_reverse),
    ]
