# Generated by Django 5.2.5 on 2025-09-18 05:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_create_sas_product_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='sync_type',
            field=models.CharField(choices=[('lotto', 'LOTTO Clubs'), ('sas', 'SAS Clubs'), ('tus', 'TUS Schools')], help_text='Type of sync operation', max_length=10),
        ),
        migrations.CreateModel(
            name='TUSGeneralCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name', max_length=255, unique=True)),
                ('woo_category_id', models.PositiveIntegerField(help_text='WooCommerce category ID', unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Category image URL', max_length=500, null=True)),
                ('product_count', models.PositiveIntegerField(default=0, help_text='Number of products in this category')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order for sorting')),
                ('is_featured', models.BooleanField(default=False, help_text='Is this a featured category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='clubs.tusgeneralcategory')),
            ],
            options={
                'verbose_name': 'TUS General Category',
                'verbose_name_plural': 'TUS General Categories',
                'db_table': 'tus_general_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TUSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location name (e.g., Pakuranga, Auckland)', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name', max_length=255, unique=True)),
                ('woo_category_id', models.PositiveIntegerField(help_text='WooCommerce category ID for this location', unique=True)),
                ('description', models.TextField(blank=True, help_text='Location description', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Location image URL', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the location is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_location', models.ForeignKey(blank=True, help_text='Parent location for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_locations', to='clubs.tuslocation')),
            ],
            options={
                'verbose_name': 'TUS Location',
                'verbose_name_plural': 'TUS Locations',
                'db_table': 'tus_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TUSProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name', max_length=255)),
                ('woo_product_id', models.PositiveIntegerField(help_text='WooCommerce product ID', unique=True)),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('grouped', 'Grouped'), ('external', 'External/Affiliate'), ('variable', 'Variable')], default='simple', help_text='Product type', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Is featured product')),
                ('price', models.DecimalField(decimal_places=2, help_text='Current product price', max_digits=10)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, help_text='Regular price', max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price', max_digits=10, null=True)),
                ('on_sale', models.BooleanField(default=False, help_text='Is product on sale')),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('short_description', models.TextField(blank=True, help_text='Short product description', null=True)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100, null=True)),
                ('stock_status', models.CharField(choices=[('instock', 'In Stock'), ('outofstock', 'Out of Stock'), ('onbackorder', 'On Backorder')], default='instock', help_text='Stock status', max_length=20)),
                ('manage_stock', models.BooleanField(default=False, help_text='Manage stock at product level')),
                ('stock_quantity', models.IntegerField(blank=True, help_text='Stock quantity', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Primary product image URL', max_length=500, null=True)),
                ('gallery_urls', models.JSONField(blank=True, help_text='Gallery image URLs', null=True)),
                ('weight', models.CharField(blank=True, help_text='Product weight', max_length=50, null=True)),
                ('dimensions', models.JSONField(blank=True, help_text='Product dimensions', null=True)),
                ('tags', models.JSONField(blank=True, help_text='Product tags', null=True)),
                ('attributes', models.JSONField(blank=True, help_text='Product attributes', null=True)),
                ('woo_categories', models.JSONField(blank=True, help_text='WooCommerce categories from API', null=True)),
                ('meta_data', models.JSONField(blank=True, help_text='Additional meta data', null=True)),
                ('related_ids', models.JSONField(blank=True, help_text='Related product IDs', null=True)),
                ('upsell_ids', models.JSONField(blank=True, help_text='Upsell product IDs', null=True)),
                ('cross_sell_ids', models.JSONField(blank=True, help_text='Cross-sell product IDs', null=True)),
                ('parent_id', models.PositiveIntegerField(blank=True, help_text='Parent product ID for variations', null=True)),
                ('grouped_products', models.JSONField(blank=True, help_text='Grouped product IDs', null=True)),
                ('default_attributes', models.JSONField(blank=True, help_text='Default attributes for variable products', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TUS Product',
                'verbose_name_plural': 'TUS Products',
                'db_table': 'tus_products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['stock_status'], name='tus_product_stock_s_f2fffc_idx'), models.Index(fields=['woo_product_id'], name='tus_product_woo_pro_6e925d_idx'), models.Index(fields=['sku'], name='tus_product_sku_2c646e_idx'), models.Index(fields=['price'], name='tus_product_price_66ef72_idx'), models.Index(fields=['featured'], name='tus_product_feature_5d2a37_idx'), models.Index(fields=['on_sale'], name='tus_product_on_sale_03a5d2_idx'), models.Index(fields=['created_at'], name='tus_product_created_4a5547_idx'), models.Index(fields=['parent_id'], name='tus_product_parent__3739b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TUSProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('gender', 'Gender'), ('style', 'Style'), ('length', 'Length'), ('fit', 'Fit'), ('other', 'Other')], help_text='Type of variation', max_length=50)),
                ('variation_value', models.CharField(help_text="Variation value (e.g., 'Size 10', 'Navy', 'Boys')", max_length=255)),
                ('woo_variation_id', models.PositiveIntegerField(help_text='WooCommerce variation ID', unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Variation price', max_digits=10)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, help_text='Regular price', max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price', max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Stock quantity for this variation')),
                ('stock_status', models.CharField(choices=[('instock', 'In Stock'), ('outofstock', 'Out of Stock'), ('onbackorder', 'On Backorder')], default='instock', help_text='Stock status', max_length=20)),
                ('sku', models.CharField(blank=True, help_text='Variation SKU', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this variation is active')),
                ('attributes', models.JSONField(blank=True, help_text='WooCommerce variation attributes', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Variation-specific image URL', max_length=500, null=True)),
                ('weight', models.CharField(blank=True, help_text='Variation weight', max_length=50, null=True)),
                ('dimensions', models.JSONField(blank=True, help_text='Variation dimensions', null=True)),
                ('menu_order', models.PositiveIntegerField(default=0, help_text='Sort order for variations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='clubs.tusproduct')),
            ],
            options={
                'verbose_name': 'TUS Product Variation',
                'verbose_name_plural': 'TUS Product Variations',
                'db_table': 'tus_product_variations',
                'ordering': ['product', 'menu_order', 'variation_type', 'variation_value'],
            },
        ),
        migrations.CreateModel(
            name='TUSSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='School name', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name', max_length=255, unique=True)),
                ('school_type', models.CharField(choices=[('Primary', 'Primary School'), ('Intermediate', 'Intermediate School'), ('Secondary', 'Secondary School'), ('Combined', 'Combined School'), ('Special', 'Special School'), ('Early Childhood', 'Early Childhood'), ('Tertiary', 'Tertiary Institution'), ('Other', 'Other')], default='Secondary', help_text='Type of school', max_length=20)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('website', models.URLField(blank=True, help_text='School website URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('address', models.TextField(blank=True, help_text='School physical address', null=True)),
                ('woo_category_id', models.PositiveIntegerField(help_text='WooCommerce category ID', unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='School logo URL', max_length=500, null=True)),
                ('banner_url', models.URLField(blank=True, help_text='School banner image URL', max_length=500, null=True)),
                ('enrollment_number', models.PositiveIntegerField(blank=True, help_text='Number of enrolled students', null=True)),
                ('decile_rating', models.PositiveSmallIntegerField(blank=True, help_text='School decile rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the school is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='Location this school belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='clubs.tuslocation')),
            ],
            options={
                'verbose_name': 'TUS School',
                'verbose_name_plural': 'TUS Schools',
                'db_table': 'tus_schools',
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TUSSchoolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name', max_length=255)),
                ('woo_category_id', models.PositiveIntegerField(help_text='WooCommerce category ID', unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
                ('product_count', models.PositiveIntegerField(default=0, help_text='Number of products in this category')),
                ('image_url', models.URLField(blank=True, help_text='Category image URL', max_length=500, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order within school')),
                ('is_featured', models.BooleanField(default=False, help_text='Is this a featured category for the school')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='clubs.tusschool')),
            ],
            options={
                'verbose_name': 'TUS School Category',
                'verbose_name_plural': 'TUS School Categories',
                'db_table': 'tus_school_categories',
                'ordering': ['school', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TUSProductCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary category for the product')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sort order within the category')),
                ('woo_category_id', models.PositiveIntegerField(help_text='WooCommerce category ID from API')),
                ('date_assigned', models.DateTimeField(auto_now_add=True, help_text='When product was assigned to category')),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='Last sync with WooCommerce')),
                ('general_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='clubs.tusgeneralcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='clubs.tusproduct')),
                ('school_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='clubs.tusschoolcategory')),
            ],
            options={
                'verbose_name': 'TUS Product Category Assignment',
                'verbose_name_plural': 'TUS Product Category Assignments',
                'db_table': 'tus_product_category_assignments',
                'ordering': ['sort_order', 'product__name'],
            },
        ),
        migrations.AddIndex(
            model_name='tusgeneralcategory',
            index=models.Index(fields=['is_active', 'is_featured'], name='tus_general_is_acti_ca4f41_idx'),
        ),
        migrations.AddIndex(
            model_name='tusgeneralcategory',
            index=models.Index(fields=['woo_category_id'], name='tus_general_woo_cat_a582f9_idx'),
        ),
        migrations.AddIndex(
            model_name='tusgeneralcategory',
            index=models.Index(fields=['parent_category'], name='tus_general_parent__5965fa_idx'),
        ),
        migrations.AddIndex(
            model_name='tusgeneralcategory',
            index=models.Index(fields=['display_order'], name='tus_general_display_27fb8e_idx'),
        ),
        migrations.AddIndex(
            model_name='tuslocation',
            index=models.Index(fields=['is_active'], name='tus_locatio_is_acti_625f96_idx'),
        ),
        migrations.AddIndex(
            model_name='tuslocation',
            index=models.Index(fields=['woo_category_id'], name='tus_locatio_woo_cat_359172_idx'),
        ),
        migrations.AddIndex(
            model_name='tuslocation',
            index=models.Index(fields=['parent_location'], name='tus_locatio_parent__1ad2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='tusproductvariation',
            index=models.Index(fields=['product', 'is_active'], name='tus_product_product_8c1dda_idx'),
        ),
        migrations.AddIndex(
            model_name='tusproductvariation',
            index=models.Index(fields=['woo_variation_id'], name='tus_product_woo_var_f313da_idx'),
        ),
        migrations.AddIndex(
            model_name='tusproductvariation',
            index=models.Index(fields=['variation_type', 'variation_value'], name='tus_product_variati_53a206_idx'),
        ),
        migrations.AddIndex(
            model_name='tusproductvariation',
            index=models.Index(fields=['stock_quantity'], name='tus_product_stock_q_7bd331_idx'),
        ),
        migrations.AddIndex(
            model_name='tusproductvariation',
            index=models.Index(fields=['menu_order'], name='tus_product_menu_or_033472_idx'),
        ),
        migrations.AddIndex(
            model_name='tusproductvariation',
            index=models.Index(fields=['created_at'], name='tus_product_created_b74d3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tusproductvariation',
            unique_together={('product', 'variation_type', 'variation_value')},
        ),
        migrations.AddIndex(
            model_name='tusschool',
            index=models.Index(fields=['location', 'is_active'], name='tus_schools_locatio_04c948_idx'),
        ),
        migrations.AddIndex(
            model_name='tusschool',
            index=models.Index(fields=['woo_category_id'], name='tus_schools_woo_cat_db89ef_idx'),
        ),
        migrations.AddIndex(
            model_name='tusschool',
            index=models.Index(fields=['school_type'], name='tus_schools_school__49e0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='tusschool',
            index=models.Index(fields=['created_at'], name='tus_schools_created_45ecf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tusschool',
            unique_together={('location', 'name')},
        ),
        migrations.AddIndex(
            model_name='tusschoolcategory',
            index=models.Index(fields=['school', 'product_count'], name='tus_school__school__ece239_idx'),
        ),
        migrations.AddIndex(
            model_name='tusschoolcategory',
            index=models.Index(fields=['woo_category_id'], name='tus_school__woo_cat_d07fea_idx'),
        ),
        migrations.AddIndex(
            model_name='tusschoolcategory',
            index=models.Index(fields=['display_order'], name='tus_school__display_c12c01_idx'),
        ),
        migrations.AddIndex(
            model_name='tusschoolcategory',
            index=models.Index(fields=['created_at'], name='tus_school__created_bac63d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tusschoolcategory',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='tusproductcategoryassignment',
            index=models.Index(fields=['product', 'is_primary'], name='tus_product_product_aa248e_idx'),
        ),
        migrations.AddIndex(
            model_name='tusproductcategoryassignment',
            index=models.Index(fields=['school_category', 'sort_order'], name='tus_product_school__40bad2_idx'),
        ),
        migrations.AddIndex(
            model_name='tusproductcategoryassignment',
            index=models.Index(fields=['general_category', 'sort_order'], name='tus_product_general_e9f1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='tusproductcategoryassignment',
            index=models.Index(fields=['woo_category_id'], name='tus_product_woo_cat_1c0201_idx'),
        ),
        migrations.AddIndex(
            model_name='tusproductcategoryassignment',
            index=models.Index(fields=['date_assigned'], name='tus_product_date_as_57c2ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tusproductcategoryassignment',
            unique_together={('product', 'school_category', 'general_category')},
        ),
    ]
