# Generated by Django 5.2.6 on 2025-11-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_lottoclub_cin7_company_name_lottoclub_cin7_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_billing_address1',
            field=models.CharField(blank=True, help_text='CIN7 Billing address line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_billing_address2',
            field=models.CharField(blank=True, help_text='CIN7 Billing address line 2', max_length=255),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_billing_city',
            field=models.CharField(blank=True, help_text='CIN7 Billing city', max_length=100),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_billing_postcode',
            field=models.CharField(blank=True, help_text='CIN7 Billing postcode', max_length=20),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_billing_state',
            field=models.CharField(blank=True, help_text='CIN7 Billing state', max_length=100),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_delivery_address1',
            field=models.CharField(blank=True, help_text='CIN7 Delivery address line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_delivery_address2',
            field=models.CharField(blank=True, help_text='CIN7 Delivery address line 2', max_length=255),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_delivery_city',
            field=models.CharField(blank=True, help_text='CIN7 Delivery city', max_length=100),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_delivery_postcode',
            field=models.CharField(blank=True, help_text='CIN7 Delivery postcode', max_length=20),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_delivery_state',
            field=models.CharField(blank=True, help_text='CIN7 Delivery state', max_length=100),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_first_name',
            field=models.CharField(blank=True, help_text='CIN7 Contact first name', max_length=100),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_last_name',
            field=models.CharField(blank=True, help_text='CIN7 Contact last name', max_length=100),
        ),
        migrations.AddField(
            model_name='lottoclub',
            name='cin7_phone',
            field=models.CharField(blank=True, help_text='CIN7 Contact phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_billing_address1',
            field=models.CharField(blank=True, help_text='CIN7 Billing address line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_billing_address2',
            field=models.CharField(blank=True, help_text='CIN7 Billing address line 2', max_length=255),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_billing_city',
            field=models.CharField(blank=True, help_text='CIN7 Billing city', max_length=100),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_billing_postcode',
            field=models.CharField(blank=True, help_text='CIN7 Billing postcode', max_length=20),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_billing_state',
            field=models.CharField(blank=True, help_text='CIN7 Billing state', max_length=100),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_delivery_address1',
            field=models.CharField(blank=True, help_text='CIN7 Delivery address line 1', max_length=255),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_delivery_address2',
            field=models.CharField(blank=True, help_text='CIN7 Delivery address line 2', max_length=255),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_delivery_city',
            field=models.CharField(blank=True, help_text='CIN7 Delivery city', max_length=100),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_delivery_postcode',
            field=models.CharField(blank=True, help_text='CIN7 Delivery postcode', max_length=20),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_delivery_state',
            field=models.CharField(blank=True, help_text='CIN7 Delivery state', max_length=100),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_first_name',
            field=models.CharField(blank=True, help_text='CIN7 Contact first name', max_length=100),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_last_name',
            field=models.CharField(blank=True, help_text='CIN7 Contact last name', max_length=100),
        ),
        migrations.AddField(
            model_name='sasclub',
            name='cin7_phone',
            field=models.CharField(blank=True, help_text='CIN7 Contact phone number', max_length=50),
        ),
    ]
