# Generated by Django 5.2.6 on 2025-10-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_populate_institution_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sasproduct',
            name='style_code',
            field=models.CharField(blank=True, help_text='Product style code', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='sasproduct',
            index=models.Index(fields=['style_code'], name='sas_product_style_c_9e32a5_idx'),
        ),
    ]
