# Generated by Django 5.2.6 on 2025-10-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_sasproduct_style_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottoproduct',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Product barcode', max_length=100),
        ),
        migrations.AddField(
            model_name='lottoproduct',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price from supplier', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lottoproduct',
            name='last_price_update',
            field=models.DateTimeField(blank=True, help_text='Last price update timestamp', null=True),
        ),
        migrations.AddField(
            model_name='lottoproduct',
            name='margin_75_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price with 75% margin', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sasproduct',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Product barcode', max_length=100),
        ),
        migrations.AddField(
            model_name='sasproduct',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price from supplier', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sasproduct',
            name='last_price_update',
            field=models.DateTimeField(blank=True, help_text='Last price update timestamp', null=True),
        ),
        migrations.AddField(
            model_name='sasproduct',
            name='margin_75_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price with 75% margin', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tusproduct',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Product barcode', max_length=100),
        ),
        migrations.AddField(
            model_name='tusproduct',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price from supplier', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tusproduct',
            name='last_price_update',
            field=models.DateTimeField(blank=True, help_text='Last price update timestamp', null=True),
        ),
        migrations.AddField(
            model_name='tusproduct',
            name='margin_75_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price with 75% margin', max_digits=10, null=True),
        ),
    ]
