# Generated by Django 5.2.6 on 2025-10-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_add_pricing_fields_to_tus_sas_lotto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottoproduct',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage applied', max_digits=5, null=True),
        ),
    ]
