# Generated by Django 5.2.6 on 2025-10-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_add_discount_percentage_to_lotto_sas_tus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sasproduct',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage applied', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tusproduct',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage applied', max_digits=5, null=True),
        ),
    ]
