# Generated by Django 5.2.5 on 2025-09-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(db_index=True, max_length=10, unique=True)),
                ('org_name', models.CharField(db_index=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact1_name', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('add1_line1', models.CharField(blank=True, max_length=200)),
                ('add1_suburb', models.CharField(blank=True, max_length=100)),
                ('add1_city', models.CharField(blank=True, max_length=100)),
                ('add2_line1', models.CharField(blank=True, max_length=200)),
                ('add2_suburb', models.CharField(blank=True, max_length=100)),
                ('add2_city', models.CharField(blank=True, max_length=100)),
                ('add2_postal_code', models.CharField(blank=True, max_length=10)),
                ('urban_rural_indicator', models.CharField(blank=True, max_length=100)),
                ('org_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('definition', models.TextField(blank=True)),
                ('authority', models.CharField(blank=True, max_length=50)),
                ('school_donations', models.TextField(blank=True)),
                ('coed_status', models.CharField(blank=True, max_length=50)),
                ('kme_peak_body', models.CharField(blank=True, max_length=100)),
                ('takiwa', models.CharField(blank=True, max_length=100)),
                ('territorial_authority', models.CharField(blank=True, max_length=150)),
                ('regional_council', models.CharField(blank=True, max_length=100)),
                ('local_office_name', models.CharField(blank=True, max_length=100)),
                ('education_region', models.CharField(blank=True, max_length=100)),
                ('general_electorate', models.CharField(blank=True, max_length=100)),
                ('maori_electorate', models.CharField(blank=True, max_length=100)),
                ('statistical_area_2_code', models.CharField(blank=True, max_length=20)),
                ('statistical_area_2_description', models.CharField(blank=True, max_length=200)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('col_id', models.CharField(blank=True, max_length=20)),
                ('col_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('enrolment_scheme', models.CharField(blank=True, max_length=10)),
                ('eqi_index', models.CharField(blank=True, max_length=10)),
                ('roll_date', models.DateTimeField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
                ('european', models.IntegerField(default=0)),
                ('maori', models.IntegerField(default=0)),
                ('pacific', models.IntegerField(default=0)),
                ('asian', models.IntegerField(default=0)),
                ('melaa', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('international', models.IntegerField(default=0)),
                ('isolation_index', models.CharField(blank=True, max_length=10)),
                ('language_of_instruction', models.CharField(blank=True, max_length=100)),
                ('boarding_facilities', models.CharField(blank=True, max_length=10)),
                ('cohort_entry', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('date_school_opened', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['org_name'],
                'indexes': [models.Index(fields=['org_type', 'org_name'], name='schools_sch_org_typ_6f065d_idx'), models.Index(fields=['regional_council', 'org_name'], name='schools_sch_regiona_d201fa_idx'), models.Index(fields=['territorial_authority', 'org_name'], name='schools_sch_territo_c7917a_idx')],
            },
        ),
    ]
