# Generated by Django 5.2.6 on 2025-10-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cin7Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin7_id', models.IntegerField(db_index=True, help_text='Cin7 product ID')),
                ('code', models.CharField(db_index=True, help_text='Product SKU/Code', max_length=100)),
                ('style_code', models.CharField(blank=True, db_index=True, help_text='Product style code', max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Product barcode', max_length=100)),
                ('name', models.CharField(help_text='Product name', max_length=500)),
                ('category', models.CharField(blank=True, help_text='Cin7 category', max_length=200)),
                ('brand', models.CharField(blank=True, help_text='Product brand', max_length=200)),
                ('cost_nzd', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price in NZD', max_digits=10, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, help_text='Retail price (RRP)', max_digits=10, null=True)),
                ('margin_75_price', models.DecimalField(blank=True, decimal_places=2, help_text='75% margin price (Cost ÷ 0.25)', max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount from 75% margin', max_digits=5, null=True)),
                ('stock_available', models.IntegerField(blank=True, help_text='Available stock quantity', null=True)),
                ('matched', models.BooleanField(db_index=True, default=False, help_text='Whether matched to local product')),
                ('matched_product_id', models.IntegerField(blank=True, help_text='Local product ID if matched', null=True)),
                ('matched_variation_id', models.IntegerField(blank=True, help_text='Local variation ID if matched', null=True)),
                ('match_method', models.CharField(blank=True, help_text='How product was matched', max_length=100)),
                ('price_type', models.CharField(db_index=True, help_text='Price type: TUS, LOTTO, SAS, Wholesale', max_length=50)),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether prices have been applied')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When prices were applied', null=True)),
                ('fetch_session_id', models.CharField(db_index=True, help_text='Session ID from fetch operation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Raw Cin7 API response', null=True)),
            ],
            options={
                'verbose_name': 'Cin7 Product',
                'verbose_name_plural': 'Cin7 Products',
                'db_table': 'cin7_products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fetch_session_id', 'matched'], name='cin7_produc_fetch_s_f56455_idx'), models.Index(fields=['price_type', 'processed'], name='cin7_produc_price_t_996225_idx'), models.Index(fields=['created_at', 'fetch_session_id'], name='cin7_produc_created_24f603_idx')],
            },
        ),
    ]
