# Generated by Django 5.2.6 on 2025-11-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_add_cin7_reference_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tusproductvariation',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Variation barcode (for CIN7 matching)', max_length=100, null=True),
        ),
    ]
