# Generated by Django 5.2.6 on 2025-10-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_cin7product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cin7product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='cin7product',
            name='margin_75_price',
        ),
    ]
