# Generated by Django 5.2.6 on 2025-10-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleschool',
            name='logo',
            field=models.URLField(blank=True, help_text='School logo image URL', max_length=500, null=True),
        ),
    ]
