# Generated by Django 5.2.8 on 2025-12-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_add_cin7_product_cache_timestamp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cin7product',
            new_name='cin7_produc_price_t_f92b9d_idx',
            old_name='cin7_produc_price_t_idx',
        ),
        migrations.AddField(
            model_name='cin7product',
            name='cin7_modified_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='CIN7 product modification date if available', null=True),
        ),
        migrations.AddField(
            model_name='cin7product',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash of pricing data for change detection', max_length=64),
        ),
        migrations.AddField(
            model_name='cin7product',
            name='is_initial_sync',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record is from initial sync'),
        ),
        migrations.AddIndex(
            model_name='cin7product',
            index=models.Index(fields=['price_type', 'is_initial_sync'], name='cin7_produc_price_t_a88051_idx'),
        ),
        migrations.AddIndex(
            model_name='cin7product',
            index=models.Index(fields=['cin7_id', 'price_type'], name='cin7_produc_cin7_id_9a4e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='cin7product',
            index=models.Index(fields=['data_hash'], name='cin7_produc_data_ha_7285cf_idx'),
        ),
    ]
