# Generated by Django 5.2.6 on 2025-11-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_add_barcode_to_tus_product_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tusschool',
            name='cin7_company_name',
            field=models.CharField(blank=True, help_text='CIN7 Contact company name', max_length=255),
        ),
        migrations.AddField(
            model_name='tusschool',
            name='cin7_email',
            field=models.EmailField(blank=True, help_text='CIN7 Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='tusschool',
            name='cin7_id',
            field=models.CharField(blank=True, db_index=True, help_text='CIN7 Contact ID for sales orders', max_length=50),
        ),
        migrations.AddField(
            model_name='wholesaleschool',
            name='cin7_company_name',
            field=models.CharField(blank=True, help_text='CIN7 Contact company name', max_length=255),
        ),
        migrations.AddField(
            model_name='wholesaleschool',
            name='cin7_contact_id',
            field=models.CharField(blank=True, db_index=True, help_text='CIN7 Contact ID for sales orders', max_length=50),
        ),
        migrations.AddField(
            model_name='wholesaleschool',
            name='cin7_email',
            field=models.EmailField(blank=True, help_text='CIN7 Contact email address', max_length=254),
        ),
        migrations.CreateModel(
            name='CIN7Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin7_id', models.IntegerField(db_index=True, help_text='CIN7 Contact ID', unique=True)),
                ('company', models.CharField(db_index=True, help_text='Company name', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('first_name', models.CharField(blank=True, help_text='Contact first name', max_length=100)),
                ('last_name', models.CharField(blank=True, help_text='Contact last name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last sync from CIN7 API', null=True)),
            ],
            options={
                'verbose_name': 'CIN7 Contact',
                'verbose_name_plural': 'CIN7 Contacts',
                'db_table': 'cin7_contacts_mapping',
                'ordering': ['company'],
                'indexes': [models.Index(fields=['company'], name='cin7_contac_company_bed51f_idx'), models.Index(fields=['cin7_id'], name='cin7_contac_cin7_id_0b6cf2_idx')],
            },
        ),
    ]
