# Generated by Django 5.2.6 on 2025-10-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_wholesaleschool_logo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wholesaleschool',
            index=models.Index(fields=['slug'], name='wholesale_s_slug_dfe389_idx'),
        ),
    ]
