# Generated by Django 5.2.6 on 2025-11-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_add_sync_log_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='synclog',
            new_name='sync_logs_session_15e144_idx',
            old_name='sync_logs_session_8f82ea_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='sync_logs_entity__3d3906_idx',
            old_name='sync_logs_entity__3f5af8_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='sync_logs_level_abad05_idx',
            old_name='sync_logs_level_e66f6c_idx',
        ),
    ]
