# Generated by Django 5.2.8 on 2026-02-13 05:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Store name (e.g., 'Botany Store', 'Chartwell Store')", max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Store email address', max_length=254)),
                ('address_line1', models.CharField(help_text='Street address', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Additional address information (optional)', max_length=255)),
                ('suburb', models.CharField(help_text='Suburb', max_length=100)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional store information or notes')),
                ('is_active', models.BooleanField(default=True, help_text='Is this store currently active?')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which stores should be displayed (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schools', models.ManyToManyField(blank=True, help_text='Schools serviced by this store', related_name='stores', to='schools.school')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week')),
                ('opening_time', models.TimeField(help_text='Opening time (e.g., 09:00)')),
                ('closing_time', models.TimeField(help_text='Closing time (e.g., 17:00)')),
                ('is_closed', models.BooleanField(default=False, help_text='Is the store closed on this day?')),
                ('notes', models.CharField(blank=True, help_text='Special notes for this day (optional)', max_length=255)),
                ('store', models.ForeignKey(help_text='Store these hours apply to', on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Opening Hours',
                'verbose_name_plural': 'Store Opening Hours',
                'ordering': ['store', 'day_of_week'],
                'unique_together': {('store', 'day_of_week')},
            },
        ),
    ]
