# Generated by Django 5.2.8 on 2026-02-13 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeopeninghours',
            options={'ordering': ['store', 'period', 'day_of_week'], 'verbose_name': 'Store Opening Hours', 'verbose_name_plural': 'Store Opening Hours'},
        ),
        migrations.CreateModel(
            name='StorePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Period name (e.g., 'Term 1 2024', 'Christmas 2024')", max_length=200)),
                ('period_type', models.CharField(choices=[('term', 'Term Time'), ('holiday', 'School Holidays'), ('christmas', 'Christmas Period'), ('easter', 'Easter Period'), ('special', 'Special Event'), ('other', 'Other')], default='other', help_text='Type of period', max_length=20)),
                ('start_date', models.DateField(help_text='Period start date')),
                ('end_date', models.DateField(help_text='Period end date')),
                ('priority', models.IntegerField(default=0, help_text='Priority for overlapping periods (higher number = higher priority)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this period active? (can be disabled without deleting)')),
                ('description', models.TextField(blank=True, help_text='Description or notes about this period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(help_text='Store this period applies to', on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='stores.store')),
            ],
            options={
                'verbose_name': 'Store Period',
                'verbose_name_plural': 'Store Periods',
                'ordering': ['-priority', 'start_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='storeopeninghours',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storeopeninghours',
            name='period',
            field=models.ForeignKey(blank=True, help_text='Period these hours apply to (null = default/regular hours)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='stores.storeperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='storeopeninghours',
            unique_together={('store', 'period', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='storeopeninghours',
            index=models.Index(fields=['store', 'period', 'day_of_week'], name='stores_stor_store_i_98a49f_idx'),
        ),
        migrations.AddIndex(
            model_name='storeperiod',
            index=models.Index(fields=['store', 'start_date', 'end_date'], name='stores_stor_store_i_e6ed6a_idx'),
        ),
        migrations.AddIndex(
            model_name='storeperiod',
            index=models.Index(fields=['start_date', 'end_date', 'is_active'], name='stores_stor_start_d_81c9fd_idx'),
        ),
    ]
