# Generated by Django 5.2.6 on 2025-10-09 08:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(editable=False, help_text='Auto-generated quotation number (Q-YYYYMMDD-XXXX)', max_length=50, unique=True)),
                ('institution_object_id', models.PositiveIntegerField(help_text='ID of the institution')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Current quotation status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Quotation expiry date', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal before tax and discount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage applied to subtotal', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed discount amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Tax percentage (VAT)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated tax amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this quotation')),
                ('customer_notes', models.TextField(blank=True, help_text='Notes visible to the customer')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms and conditions for this quotation')),
                ('version', models.PositiveIntegerField(default=1, help_text='Quotation version number')),
                ('reference_number', models.CharField(blank=True, help_text='External reference number (PO, etc.)', max_length=100)),
                ('is_locked', models.BooleanField(default=False, help_text='Whether quotation is locked from editing')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this quotation (sales rep/account manager/customer)', on_delete=django.db.models.deletion.PROTECT, related_name='quotations_created', to=settings.AUTH_USER_MODEL)),
                ('institution_content_type', models.ForeignKey(help_text='Type of institution (school or club)', limit_choices_to={'model__in': ['school', 'wholesaleschool', 'lottoclub', 'sasclub']}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('rejected_by', models.ForeignKey(blank=True, help_text='User who rejected this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_rejected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'db_table': 'quotations',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_quotation', 'Can approve quotations'), ('can_reject_quotation', 'Can reject quotations'), ('can_view_all_quotations', 'Can view all quotations')],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_object_id', models.PositiveIntegerField(help_text='ID of the product')),
                ('product_snapshot', models.JSONField(default=dict, help_text='Snapshot of product data at time of quotation creation')),
                ('product_name', models.CharField(help_text='Product name at time of quote', max_length=255)),
                ('product_sku', models.CharField(blank=True, help_text='Product SKU', max_length=100)),
                ('product_image_url', models.URLField(blank=True, help_text='Product image URL', max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this item', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of quotation', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('variations', models.JSONField(blank=True, default=dict, help_text='Product variations (size, color, etc.)')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total (quantity × unit_price)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Notes about this item')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in quotation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_content_type', models.ForeignKey(help_text='Type of product', limit_choices_to={'model__in': ['wholesaleproduct', 'lottoproduct', 'sasproduct', 'tusproduct']}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('quotation', models.ForeignKey(help_text='Parent quotation', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
                'db_table': 'quotation_items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Version number')),
                ('snapshot_data', models.JSONField(help_text='Complete snapshot of quotation data')),
                ('change_description', models.TextField(blank=True, help_text='Description of what changed in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_versions_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(help_text='Parent quotation', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Version',
                'verbose_name_plural': 'Quotation Versions',
                'db_table': 'quotation_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInstitutionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_object_id', models.PositiveIntegerField(help_text='ID of the institution')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this assignment is active')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When assignment was made')),
                ('notes', models.TextField(blank=True, help_text='Notes about this assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer user', limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='institution_assignments', to=settings.AUTH_USER_MODEL)),
                ('institution_content_type', models.ForeignKey(help_text='Type of institution', limit_choices_to={'model__in': ['tusschool', 'wholesaleschool', 'lottoclub', 'sasclub']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Customer Institution Assignment',
                'verbose_name_plural': 'Customer Institution Assignments',
                'db_table': 'customer_institution_assignments',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['customer', 'is_active'], name='customer_in_custome_3eeb8b_idx'), models.Index(fields=['institution_content_type', 'institution_object_id'], name='customer_in_institu_c01f2b_idx'), models.Index(fields=['assigned_date'], name='customer_in_assigne_f89229_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer', 'institution_content_type', 'institution_object_id'), name='unique_active_customer_institution')],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_number'], name='quotations_quotati_298c04_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['created_by', 'status'], name='quotations_created_c125b9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['institution_content_type', 'institution_object_id'], name='quotations_institu_ad550a_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status', 'expires_at'], name='quotations_status_2034f9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['created_at'], name='quotations_created_ec533b_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['approved_at'], name='quotations_approve_8ac0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationitem',
            index=models.Index(fields=['quotation', 'sort_order'], name='quotation_i_quotati_864b59_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationitem',
            index=models.Index(fields=['product_content_type', 'product_object_id'], name='quotation_i_product_5f0fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationversion',
            index=models.Index(fields=['quotation', 'version_number'], name='quotation_v_quotati_6b0f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationversion',
            index=models.Index(fields=['created_at'], name='quotation_v_created_b41156_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotationversion',
            constraint=models.UniqueConstraint(fields=('quotation', 'version_number'), name='unique_quotation_version'),
        ),
    ]
