# Generated by Django 5.2.8 on 2025-12-02 07:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(editable=False, help_text='Auto-generated quotation number (Q-YYYYMMDD-XXXX)', max_length=50, unique=True)),
                ('institution_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the institution - optional', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Current quotation status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Quotation expiry date', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal before tax and discount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage applied to subtotal', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed discount amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Tax percentage (VAT)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated tax amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated shipping cost based on boxes and region', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shipping_boxes', models.PositiveIntegerField(default=0, help_text='Number of boxes required for shipping')),
                ('shipping_region', models.CharField(blank=True, help_text='NZ region for shipping rate calculation', max_length=100)),
                ('is_rural_delivery', models.BooleanField(default=False, help_text='Rural Delivery (RD) surcharge applies')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this quotation')),
                ('customer_notes', models.TextField(blank=True, help_text='Notes visible to the customer')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms and conditions for this quotation')),
                ('recipient_name', models.CharField(blank=True, help_text='Name of the quotation recipient', max_length=255)),
                ('recipient_phone', models.CharField(blank=True, help_text='Phone number of the quotation recipient', max_length=50)),
                ('recipient_address', models.TextField(blank=True, help_text='Address of the quotation recipient (combined/legacy field)')),
                ('additional_emails', models.TextField(blank=True, help_text='Additional email addresses to send quotation copies to (separated by semicolons)')),
                ('delivery_street_address', models.CharField(blank=True, help_text='Delivery street address', max_length=255)),
                ('delivery_suburb', models.CharField(blank=True, help_text='Delivery suburb', max_length=100)),
                ('delivery_city', models.CharField(blank=True, help_text='Delivery city', max_length=100)),
                ('delivery_postcode', models.CharField(blank=True, help_text='Delivery postcode', max_length=20)),
                ('delivery_state', models.CharField(blank=True, help_text='Delivery state/region', max_length=100)),
                ('version', models.PositiveIntegerField(default=1, help_text='Quotation version number')),
                ('reference_number', models.CharField(blank=True, help_text='External reference number (PO, etc.)', max_length=100)),
                ('cin7_so_number', models.CharField(blank=True, db_index=True, help_text='CIN7 Sales Order Number', max_length=100, null=True, verbose_name='CIN7 SO Number')),
                ('cin7_so_id', models.CharField(blank=True, help_text='CIN7 Sales Order ID', max_length=50, null=True, verbose_name='CIN7 SO ID')),
                ('cin7_sync_status', models.CharField(blank=True, choices=[('not_required', 'Not Required'), ('pending', 'Pending Sync'), ('syncing', 'Syncing'), ('synced', 'Synced to CIN7'), ('failed', 'Sync Failed')], default='not_required', help_text='Status of synchronization with CIN7', max_length=20, verbose_name='CIN7 Sync Status')),
                ('cin7_sync_error', models.TextField(blank=True, help_text='Error message if CIN7 sync failed', null=True, verbose_name='CIN7 Sync Error')),
                ('cin7_synced_at', models.DateTimeField(blank=True, help_text='Timestamp when quotation was synced to CIN7', null=True, verbose_name='CIN7 Synced At')),
                ('cin7_email', models.CharField(blank=True, help_text='CIN7 contact email from institution (captured at quotation creation)', max_length=255, verbose_name='CIN7 Contact Email')),
                ('cin7_first_name', models.CharField(blank=True, help_text='CIN7 contact first name from institution (captured at quotation creation)', max_length=100, verbose_name='CIN7 Contact First Name')),
                ('cin7_last_name', models.CharField(blank=True, help_text='CIN7 contact last name from institution (captured at quotation creation)', max_length=100, verbose_name='CIN7 Contact Last Name')),
                ('cin7_phone', models.CharField(blank=True, help_text='CIN7 contact phone from institution (captured at quotation creation)', max_length=50, verbose_name='CIN7 Contact Phone')),
                ('submitted_for_approval_at', models.DateTimeField(blank=True, help_text='Timestamp when quotation was submitted for account manager approval', null=True, verbose_name='Submitted for Approval At')),
                ('account_manager_approved_at', models.DateTimeField(blank=True, help_text='Timestamp when account manager approved the quotation', null=True, verbose_name='Account Manager Approved At')),
                ('customer_approved_at', models.DateTimeField(blank=True, help_text='Timestamp when customer approved the quotation', null=True, verbose_name='Customer Approved At')),
                ('approval_override_at', models.DateTimeField(blank=True, help_text='Timestamp when account manager overrode customer approval requirement', null=True, verbose_name='Approval Override At')),
                ('last_edited_at', models.DateTimeField(blank=True, help_text='Timestamp when quotation was last edited', null=True, verbose_name='Last Edited At')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether quotation is locked from editing')),
                ('account_manager', models.ForeignKey(blank=True, help_text='Account manager assigned to this quotation', limit_choices_to={'user_type': 'account_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotations_manager', to=settings.AUTH_USER_MODEL)),
                ('approval_override_by', models.ForeignKey(blank=True, help_text='Account manager who overrode customer approval requirement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_approval_override', to=settings.AUTH_USER_MODEL, verbose_name='Approval Override By')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_approved', to=settings.AUTH_USER_MODEL)),
                ('assigned_sales_rep', models.ForeignKey(blank=True, help_text='Sales representative assigned to this quotation', limit_choices_to={'user_type': 'sales_rep'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotations_sales', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this quotation (sales rep/account manager/customer)', on_delete=django.db.models.deletion.PROTECT, related_name='quotations_created', to=settings.AUTH_USER_MODEL)),
                ('customer_approved_by', models.ForeignKey(blank=True, help_text='User who gave customer approval (customer or sales rep on their behalf)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_customer_approved', to=settings.AUTH_USER_MODEL, verbose_name='Customer Approved By')),
                ('institution_content_type', models.ForeignKey(blank=True, help_text='Type of institution (school or club) - optional', limit_choices_to={'model__in': ['school', 'wholesaleschool', 'lottoclub', 'sasclub']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='User who last edited this quotation (Account Manager or Sales Rep)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By')),
                ('rejected_by', models.ForeignKey(blank=True, help_text='User who rejected this quotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_rejected', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='User who submitted the quotation for approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'db_table': 'quotations',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_quotation', 'Can approve quotations'), ('can_reject_quotation', 'Can reject quotations'), ('can_view_all_quotations', 'Can view all quotations')],
            },
        ),
        migrations.CreateModel(
            name='CIN7OrderMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cin7_order_id', models.IntegerField(help_text='CIN7 internal order ID', unique=True, verbose_name='CIN7 Order ID')),
                ('cin7_reference', models.CharField(db_index=True, help_text='CIN7 order reference number', max_length=30, verbose_name='CIN7 Reference')),
                ('cin7_stage', models.CharField(blank=True, help_text='Current stage of the order in CIN7 (e.g., Draft, Confirmed, Dispatched)', max_length=50, verbose_name='CIN7 Stage')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current synchronization status', max_length=20, verbose_name='Sync Status')),
                ('sync_attempts', models.PositiveIntegerField(default=0, help_text='Number of synchronization attempts', verbose_name='Sync Attempts')),
                ('last_sync_attempt', models.DateTimeField(auto_now=True, help_text='Timestamp of last synchronization attempt', verbose_name='Last Sync Attempt')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sync failed', verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quotation', models.OneToOneField(help_text='Quotation that was synced to CIN7', on_delete=django.db.models.deletion.PROTECT, related_name='cin7_order', to='quotations.quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'CIN7 Order Mapping',
                'verbose_name_plural': 'CIN7 Order Mappings',
                'db_table': 'cin7_order_mappings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_object_id', models.PositiveIntegerField(help_text='ID of the product')),
                ('product_snapshot', models.JSONField(default=dict, help_text='Snapshot of product data at time of quotation creation')),
                ('product_name', models.CharField(help_text='Product name at time of quote', max_length=255)),
                ('product_sku', models.CharField(blank=True, help_text='Product SKU', max_length=100)),
                ('product_image_url', models.URLField(blank=True, help_text='Product image URL', max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this item', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of quotation', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('variations', models.JSONField(blank=True, default=dict, help_text='Product variations (size, color, etc.)')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total (quantity × unit_price)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Notes about this item')),
                ('cin7_product_option_id', models.IntegerField(blank=True, db_index=True, help_text='CIN7 product option ID (variant ID) from API lookup', null=True, verbose_name='CIN7 Product Option ID')),
                ('cin7_match_method', models.CharField(blank=True, choices=[('barcode', 'Barcode Match'), ('sku', 'SKU Match'), ('database', 'Database Match')], help_text='Method used to match this item to CIN7 product option', max_length=50, verbose_name='CIN7 Match Method')),
                ('cin7_matched_at', models.DateTimeField(blank=True, help_text='Timestamp when CIN7 product option was matched', null=True, verbose_name='CIN7 Matched At')),
                ('is_addon', models.BooleanField(default=False, help_text='Whether this item is an addon (customization) for a base garment')),
                ('addon_type', models.CharField(blank=True, choices=[('heat_transfer', 'Heat Transfer'), ('screen_print', 'Screen Print'), ('emb_applique', 'EMB/Applique')], help_text='Type of addon customization', max_length=50, null=True)),
                ('addon_details', models.JSONField(blank=True, help_text='Addon configuration details (size, colors, stitch complexity, etc.)', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in quotation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_item', models.ForeignKey(blank=True, help_text='Parent base garment item (if this is an addon)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='quotations.quotationitem')),
                ('product_content_type', models.ForeignKey(help_text='Type of product', limit_choices_to={'model__in': ['wholesaleproduct', 'lottoproduct', 'sasproduct', 'tusproduct', 'ballstoreproduct']}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('quotation', models.ForeignKey(help_text='Parent quotation', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
                'db_table': 'quotation_items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(help_text='Version number')),
                ('snapshot_data', models.JSONField(help_text='Complete snapshot of quotation data')),
                ('changes_detail', models.JSONField(blank=True, help_text='Detailed changes including items added/removed/modified and pricing changes', null=True)),
                ('change_description', models.TextField(blank=True, help_text='Description of what changed in this version')),
                ('change_note', models.TextField(blank=True, help_text='User-provided note explaining the changes made in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_versions_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(help_text='Parent quotation', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Version',
                'verbose_name_plural': 'Quotation Versions',
                'db_table': 'quotation_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_weight_limit_kg', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Maximum weight capacity per box in kilograms', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('product_capacities', models.JSONField(default=dict, help_text='Product type to quantity capacity mapping for standard 20kg box')),
                ('shipping_rates', models.JSONField(default=dict, help_text='Shipping costs by region and weight')),
                ('rd_delivery_surcharge', models.DecimalField(decimal_places=2, default=Decimal('6.50'), help_text='Additional charge for Rural Delivery (RD) addresses', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Settings',
                'verbose_name_plural': 'Shipping Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='GST/VAT percentage applied to quotations', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('quotation_validity_days', models.PositiveIntegerField(default=30, help_text='Default number of days a quotation remains valid', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated the settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='CustomerInstitutionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_object_id', models.PositiveIntegerField(help_text='ID of the institution')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this assignment is active')),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When assignment was made')),
                ('notes', models.TextField(blank=True, help_text='Notes about this assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer user', limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='institution_assignments', to=settings.AUTH_USER_MODEL)),
                ('institution_content_type', models.ForeignKey(help_text='Type of institution', limit_choices_to={'model__in': ['tusschool', 'wholesaleschool', 'lottoclub', 'sasclub']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Customer Institution Assignment',
                'verbose_name_plural': 'Customer Institution Assignments',
                'db_table': 'customer_institution_assignments',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['customer', 'is_active'], name='customer_in_custome_3eeb8b_idx'), models.Index(fields=['institution_content_type', 'institution_object_id'], name='customer_in_institu_c01f2b_idx'), models.Index(fields=['assigned_date'], name='customer_in_assigne_f89229_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer', 'institution_content_type', 'institution_object_id'), name='unique_active_customer_institution')],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_number'], name='quotations_quotati_298c04_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['created_by', 'status'], name='quotations_created_c125b9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['institution_content_type', 'institution_object_id'], name='quotations_institu_ad550a_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status', 'expires_at'], name='quotations_status_2034f9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['created_at'], name='quotations_created_ec533b_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['approved_at'], name='quotations_approve_8ac0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='cin7ordermapping',
            index=models.Index(fields=['cin7_order_id'], name='cin7_order__cin7_or_552ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='cin7ordermapping',
            index=models.Index(fields=['cin7_reference'], name='cin7_order__cin7_re_e16703_idx'),
        ),
        migrations.AddIndex(
            model_name='cin7ordermapping',
            index=models.Index(fields=['sync_status', 'last_sync_attempt'], name='cin7_order__sync_st_ac5af1_idx'),
        ),
        migrations.AddIndex(
            model_name='cin7ordermapping',
            index=models.Index(fields=['created_at'], name='cin7_order__created_80f460_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationitem',
            index=models.Index(fields=['quotation', 'sort_order'], name='quotation_i_quotati_864b59_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationitem',
            index=models.Index(fields=['product_content_type', 'product_object_id'], name='quotation_i_product_5f0fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationversion',
            index=models.Index(fields=['quotation', 'version_number'], name='quotation_v_quotati_6b0f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationversion',
            index=models.Index(fields=['created_at'], name='quotation_v_created_b41156_idx'),
        ),
        migrations.AddConstraint(
            model_name='quotationversion',
            constraint=models.UniqueConstraint(fields=('quotation', 'version_number'), name='unique_quotation_version'),
        ),
    ]
