# Generated by Django 5.2.6 on 2025-10-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinstitutionassignment',
            name='institution_content_type',
            field=models.ForeignKey(help_text='Type of institution', limit_choices_to={'model__in': ['tusschool', 'wholesaleschool', 'lottoclub', 'sasclub']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
