# Generated by Django 5.2.6 on 2025-11-14 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='addon_details',
            field=models.JSONField(blank=True, help_text='Addon configuration details (size, colors, stitch complexity, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='addon_type',
            field=models.CharField(blank=True, choices=[('heat_transfer', 'Heat Transfer'), ('screen_print', 'Screen Print'), ('emb_applique', 'EMB/Applique')], help_text='Type of addon customization', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='is_addon',
            field=models.BooleanField(default=False, help_text='Whether this item is an addon (customization) for a base garment'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, help_text='Parent base garment item (if this is an addon)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='quotations.quotationitem'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product_content_type',
            field=models.ForeignKey(help_text='Type of product', limit_choices_to={'model__in': ['wholesaleproduct', 'lottoproduct', 'sasproduct', 'tusproduct', 'ballstoreproduct']}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
    ]
