# Generated by Django 5.2.8 on 2025-12-02 13:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='air_freight_surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='6% surcharge applied when Air freight is selected', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='quotation',
            name='order_label',
            field=models.CharField(blank=True, help_text='Custom label for order organization', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='order_required_date',
            field=models.DateField(blank=True, help_text='Required delivery date (minimum 6 weeks for Air, 8 weeks for Sea from order date)', null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shipping_mode',
            field=models.CharField(choices=[('sea', 'Sea Freight'), ('air', 'Air Freight')], default='sea', help_text='Shipping method for bespoke items (Sea or Air freight)', max_length=10),
        ),
    ]
