# Generated by Django 5.2.6 on 2025-10-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='recipient_address',
            field=models.TextField(blank=True, help_text='Address of the quotation recipient'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Name of the quotation recipient', max_length=255),
        ),
    ]
