# Generated by Django 5.2.6 on 2025-11-15 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotationitem_addon_details_quotationitem_addon_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='account_manager_approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when account manager approved the quotation', null=True, verbose_name='Account Manager Approved At'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cin7_so_id',
            field=models.CharField(blank=True, help_text='CIN7 Sales Order ID', max_length=50, null=True, verbose_name='CIN7 SO ID'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cin7_so_number',
            field=models.CharField(blank=True, db_index=True, help_text='CIN7 Sales Order Number', max_length=100, null=True, verbose_name='CIN7 SO Number'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cin7_sync_error',
            field=models.TextField(blank=True, help_text='Error message if CIN7 sync failed', null=True, verbose_name='CIN7 Sync Error'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cin7_sync_status',
            field=models.CharField(blank=True, choices=[('not_required', 'Not Required'), ('pending', 'Pending Sync'), ('syncing', 'Syncing'), ('synced', 'Synced to CIN7'), ('failed', 'Sync Failed')], default='not_required', help_text='Status of synchronization with CIN7', max_length=20, verbose_name='CIN7 Sync Status'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cin7_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when quotation was synced to CIN7', null=True, verbose_name='CIN7 Synced At'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted the quotation for approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitted_for_approval_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when quotation was submitted for account manager approval', null=True, verbose_name='Submitted for Approval At'),
        ),
        migrations.CreateModel(
            name='CIN7OrderMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cin7_order_id', models.IntegerField(help_text='CIN7 internal order ID', unique=True, verbose_name='CIN7 Order ID')),
                ('cin7_reference', models.CharField(db_index=True, help_text='CIN7 order reference number', max_length=30, verbose_name='CIN7 Reference')),
                ('cin7_stage', models.CharField(blank=True, help_text='Current stage of the order in CIN7 (e.g., Draft, Confirmed, Dispatched)', max_length=50, verbose_name='CIN7 Stage')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current synchronization status', max_length=20, verbose_name='Sync Status')),
                ('sync_attempts', models.PositiveIntegerField(default=0, help_text='Number of synchronization attempts', verbose_name='Sync Attempts')),
                ('last_sync_attempt', models.DateTimeField(auto_now=True, help_text='Timestamp of last synchronization attempt', verbose_name='Last Sync Attempt')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sync failed', verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quotation', models.OneToOneField(help_text='Quotation that was synced to CIN7', on_delete=django.db.models.deletion.PROTECT, related_name='cin7_order', to='quotations.quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'CIN7 Order Mapping',
                'verbose_name_plural': 'CIN7 Order Mappings',
                'db_table': 'cin7_order_mappings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cin7_order_id'], name='cin7_order__cin7_or_552ca5_idx'), models.Index(fields=['cin7_reference'], name='cin7_order__cin7_re_e16703_idx'), models.Index(fields=['sync_status', 'last_sync_attempt'], name='cin7_order__sync_st_ac5af1_idx'), models.Index(fields=['created_at'], name='cin7_order__created_80f460_idx')],
            },
        ),
    ]
