# Generated by Django 5.2.6 on 2025-10-12 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('quotations', '0002_quotation_recipient_address_quotation_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='institution_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of institution (school or club) - optional', limit_choices_to={'model__in': ['school', 'wholesaleschool', 'lottoclub', 'sasclub']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='institution_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the institution - optional', null=True),
        ),
    ]
