# Generated by Django 5.2.6 on 2025-11-15 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotation_account_manager_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when quotation was last edited', null=True, verbose_name='Last Edited At'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='User who last edited this quotation (Account Manager or Sales Rep)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_last_edited', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
    ]
