# Generated by Django 5.2.6 on 2025-10-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_add_confirmed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='additional_emails',
            field=models.TextField(blank=True, help_text='Additional email addresses to send quotation copies to (separated by semicolons)'),
        ),
    ]
