# Generated by Claude Code on 2025-11-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_add_customer_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='cin7_product_option_id',
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text='CIN7 product option ID (variant ID) from API lookup',
                null=True,
                verbose_name='CIN7 Product Option ID'
            ),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='cin7_match_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('barcode', 'Barcode Match'),
                    ('sku', 'SKU Match'),
                    ('database', 'Database Match')
                ],
                help_text='Method used to match this item to CIN7 product option',
                max_length=50,
                verbose_name='CIN7 Match Method'
            ),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='cin7_matched_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Timestamp when CIN7 product option was matched',
                null=True,
                verbose_name='CIN7 Matched At'
            ),
        ),
    ]
