# Generated by Django 5.2.6 on 2025-11-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_add_cin7_product_option_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quotation',
            name='quotation_approval_idx',
        ),
    ]
