# Generated by Django 5.2.6 on 2025-10-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_add_sales_rep_and_account_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationversion',
            name='change_note',
            field=models.TextField(blank=True, help_text='User-provided note explaining the changes made in this version'),
        ),
    ]
