# Generated by Django 5.2.6 on 2025-11-17 07:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_remove_quotation_quotation_approval_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_weight_limit_kg', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Maximum weight capacity per box in kilograms', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('product_capacities', models.JSONField(default=dict, help_text='Product type to quantity capacity mapping for standard 20kg box')),
                ('shipping_rates', models.JSONField(default=dict, help_text='Shipping costs by region and weight')),
                ('rd_delivery_surcharge', models.DecimalField(decimal_places=2, default=Decimal('6.50'), help_text='Additional charge for Rural Delivery (RD) addresses', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Settings',
                'verbose_name_plural': 'Shipping Settings',
            },
        ),
    ]
