# Generated by Django 5.2.6 on 2025-11-18 05:36

from django.db import migrations


def update_shipping_rates_structure(apps, schema_editor):
    """
    Update existing ShippingSettings instance with new 6-tier shipping rate structure.

    Old structure (3 rates):
    - local: $6.50
    - north_island: $12.50
    - south_island: $22.50

    New structure (6 rates):
    - auckland: $7.15
    - auckland_rural: $13.75
    - north_island: $14.30
    - north_island_rural: $16.50
    - south_island: $16.50
    - south_island_rural: $21.90
    """
    ShippingSettings = apps.get_model('quotations', 'ShippingSettings')

    # Check if ShippingSettings instance exists
    if not ShippingSettings.objects.exists():
        # No existing settings, will use defaults from model
        return

    # Get the singleton instance
    settings = ShippingSettings.objects.first()

    # Update to new 6-tier rate structure with region mappings
    new_shipping_rates = {
        'auckland': {
            'cost': '7.15',
            'description': 'Auckland delivery',
            'regions': ['Auckland']
        },
        'auckland_rural': {
            'cost': '13.75',
            'description': 'Auckland Rural delivery',
            'regions': ['Waikato']
        },
        'north_island': {
            'cost': '14.30',
            'description': 'North Island delivery',
            'regions': ['Wellington', 'Northland', 'Gisborne']
        },
        'north_island_rural': {
            'cost': '16.50',
            'description': 'North Island Rural delivery',
            'regions': ['Tairāwhiti', 'Hawke\'s Bay', 'Taranaki', 'Manawatū-Whanganui']
        },
        'south_island': {
            'cost': '16.50',
            'description': 'South Island delivery',
            'regions': ['Tasman', 'Nelson', 'Marlborough', 'Canterbury']
        },
        'south_island_rural': {
            'cost': '21.90',
            'description': 'South Island Rural delivery',
            'regions': ['Otago', 'Southland', 'West Coast']
        },
    }

    settings.shipping_rates = new_shipping_rates
    settings.save()


def reverse_shipping_rates_structure(apps, schema_editor):
    """
    Reverse migration - restore old 3-tier structure.
    Note: This will lose the 6-tier rate data.
    """
    ShippingSettings = apps.get_model('quotations', 'ShippingSettings')

    if not ShippingSettings.objects.exists():
        return

    settings = ShippingSettings.objects.first()

    # Restore old 3-tier structure
    old_shipping_rates = {
        'local': {
            'max_weight_kg': 20,
            'cost': '6.50',
            'description': 'Local delivery up to 20kg'
        },
        'north_island': {
            'max_weight_kg': 10,
            'cost': '12.50',
            'description': 'North Island delivery up to 10kg'
        },
        'south_island': {
            'max_weight_kg': 10,
            'cost': '22.50',
            'description': 'South Island delivery up to 10kg'
        },
    }

    settings.shipping_rates = old_shipping_rates
    settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_shippingsettings'),
    ]

    operations = [
        migrations.RunPython(
            update_shipping_rates_structure,
            reverse_code=reverse_shipping_rates_structure
        ),
    ]
