# Generated by Django 5.2.6 on 2025-10-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_quotationversion_change_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationversion',
            name='changes_detail',
            field=models.JSONField(blank=True, help_text='Detailed changes including items added/removed/modified and pricing changes', null=True),
        ),
    ]
