# Generated by Django 5.2.6 on 2025-11-18 08:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_update_shipping_rates_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_rural_delivery',
            field=models.BooleanField(default=False, help_text='Rural Delivery (RD) surcharge applies'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shipping_boxes',
            field=models.PositiveIntegerField(default=0, help_text='Number of boxes required for shipping'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated shipping cost based on boxes and region', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shipping_region',
            field=models.CharField(blank=True, help_text='NZ region for shipping rate calculation', max_length=100),
        ),
    ]
