# Generated by Django 5.2.6 on 2025-11-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_add_shipping_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='Phone number of the quotation recipient', max_length=50),
        ),
    ]
