# Generated by Django 5.2.6 on 2025-11-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_add_recipient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='delivery_city',
            field=models.CharField(blank=True, help_text='Delivery city', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_postcode',
            field=models.CharField(blank=True, help_text='Delivery postcode', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_state',
            field=models.CharField(blank=True, help_text='Delivery state/region', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_street_address',
            field=models.CharField(blank=True, help_text='Delivery street address', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_suburb',
            field=models.CharField(blank=True, help_text='Delivery suburb', max_length=100),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='recipient_address',
            field=models.TextField(blank=True, help_text='Address of the quotation recipient (combined/legacy field)'),
        ),
    ]
