# Generated by Django 5.2.6 on 2025-11-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_quotation_delivery_city_quotation_delivery_postcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='cin7_email',
            field=models.CharField(blank=True, help_text='CIN7 contact email from institution (captured at quotation creation)', max_length=255, verbose_name='CIN7 Contact Email'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cin7_first_name',
            field=models.CharField(blank=True, help_text='CIN7 contact first name from institution (captured at quotation creation)', max_length=100, verbose_name='CIN7 Contact First Name'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cin7_last_name',
            field=models.CharField(blank=True, help_text='CIN7 contact last name from institution (captured at quotation creation)', max_length=100, verbose_name='CIN7 Contact Last Name'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cin7_phone',
            field=models.CharField(blank=True, help_text='CIN7 contact phone from institution (captured at quotation creation)', max_length=50, verbose_name='CIN7 Contact Phone'),
        ),
    ]
